### ISSUE TITLE
Ban Appeal 

### ISSUE THREAD

**Issue by Nerbertgreen** [ObliqueNET/Stratos#10]
Hello, my Minecraft username is Nerbertgreen. I'd like to issue a complaint in regards to recently being banned from Oblique Pixelmon. The reason that is given when I try to join the server is: "PokeRadar". I believe that this ban is based on a falsehood. I am not and have not been using any side mods when playing on Oblique Pixelmon. I'm not sure how to prove my innocence but I have several friends who frequent the server who can vouch for me. 

I believe that this ban was based on a certain admin, whom I'm not sure of the name of, disguising as shiny pokemon and following myself and my friends around. Naturally I would chase said shiny and throw balls at it. This went on for a while, causing me to waste tons of balls. Again I'm not sure who issued the ban, but I believe it's probably the same person who was using their admin powers abusively to mess with myself and my friends. 

I've attached a screenshot of the mods currently installed on my Minecraft Pixelmon client. 
![pixelmon mods](https://user-images.githubusercontent.com/44936126/48308577-64fb8500-e536-11e8-8a1d-0d150eb567fe.png)

**Comment by lolanonymous** [comment]
The screenshot does not prove whether or not that you had radar, and given the fact that you made this appeal a day after you ban makes it even less worthwhile. Either way, I see this going nowhere other than a "he did she did" type of ordeal, where I will have to side with my staff. I will unban you on the premise that you remove pokeradar. 

Unbanned. -hrej

**Comment by Nerbertgreen** [comment]
I appreciate the unban. I would like to say that your staff, in this case, is incorrect. I have nothing to prove by lying about this, as there are plenty of other servers I can go to. I was not using PokeRadar on your server. I would recommend having a talk with your staff about using their powers to mess with players in the game (pokedisguising as shinies and following folks around). I would also recommend a requirement of proof before banning someone. There is no proof whatsoever that I was using any type of game enhancing applications. I have around 5 shiny pokemon from the entire time I've played on the server, two of which were obtained from wondertrade. Anyways good luck with your server. I may come back at a later date, as for right now though this experience has left a sour taste in my mouth.
