### ISSUE TITLE
I will burn the server to the ground

### ISSUE THREAD

**Issue by JapaneseTourism** [ObliqueNET/Stratos#107]
Mark my words you will regret fucking with me

**Comment by Hiroku** [comment]
I'm terrified!

**Comment by JapaneseTourism** [comment]
You ban people for no reason and silence them. You fucking Hillary Clinton mother fucked. I did nothing and you will pay.

**Comment by Hiroku** [comment]
We're also in an international clique bent on creating an obedient and unaware populace!

**Comment by JapaneseTourism** [comment]
I knew it
