### ISSUE TITLE
Stratos is run by Democrat nazis

### ISSUE THREAD

**Issue by JapaneseTourism** [ObliqueNET/Stratos#108]
They worship satan, hitler, and Obama on this server.

**Comment by Hiroku** [comment]
I dunno about Obama but I like the other two!

**Comment by JapaneseTourism** [comment]
Yeah Obama is the most terrifying of the 3

**Comment by Hiroku** [comment]
yeah I'll take your word for it, you seem like the kind of guy that isn't a complete embarrassment to his family
