### ISSUE TITLE
Eli giving back unsold Pokemons from market Twice causing a dupe

### ISSUE THREAD

**Issue by Somerandomguy910** [ObliqueNET/Stratos#109]
When I logged on after getting a notice that my Skorupi wasn't sold in 1 day and returned to me. Eli said the message twice and gave me a copy of my Skorupi.

![bad eli](https://user-images.githubusercontent.com/46073567/53092851-d1960080-34e3-11e9-9f4f-3a38bdd89f3b.png)

![2019-02-20_07 44 04](https://user-images.githubusercontent.com/46073567/53092873-e1ade000-34e3-11e9-9897-b54c7fc5d23a.png)

**Comment by Hiroku** [comment]
Has this happened every time, or just once? And did you do anything differently with this Skorupi? Such as taking it out of the market and putting it back up or something. Any kind of details that might make this more specific would help me immensely. Thank you for the report

**Comment by Somerandomguy910** [comment]
This the only instance of a listing expiring and this happening, I only put it up Once and didn't touch it.

**Comment by fatyg5** [comment]
Since this has seemed to be the only occurrence since Feb 27th, I'll assume something was fixed
