### ISSUE TITLE
Egg Moves from Hatched Pokemon not being able to be releaned

### ISSUE THREAD

**Issue by Somerandomguy910** [ObliqueNET/Stratos#111]
Egg Moves from a Hatched pokemon are unable to be relearned.
The Yamask used in the screenshots have these Egg Moves from the Parents:
Toxic Spikes
Imprison
Heal Block
Nasty Plot

Screenshots before deleting the moves:
![2019-02-22_11 48 42](https://user-images.githubusercontent.com/46073567/53257655-b7515380-3698-11e9-833a-45d30319abf5.png)
![2019-02-22_11 48 47](https://user-images.githubusercontent.com/46073567/53257657-b91b1700-3698-11e9-85b1-10fcb254a3e8.png)

Screenshots after deleting the moves:
![2019-02-22_11 49 26](https://user-images.githubusercontent.com/46073567/53257733-dcde5d00-3698-11e9-8255-b9d5d025ab40.png)
![2019-02-22_11 49 30](https://user-images.githubusercontent.com/46073567/53257739-df40b700-3698-11e9-8459-bd1d86874665.png)

**Comment by Rasgnarok** [comment]
Forwarded, many thanks https://www.pixelmonmod.com/tracker.php?p=2&t=13425
