### ISSUE TITLE
Spectating Battles do not show Panels for the combatants

### ISSUE THREAD

**Issue by Somerandomguy910** [ObliqueNET/Stratos#114]
While spectating a Battle, Health Bars and such do not appear during the Battle. Only the Battle Text Box. Even after re spectating the battle a few times
This is in Reforged 7.0.3
![no info](https://user-images.githubusercontent.com/46073567/53286672-fb4b6380-373f-11e9-829e-88fd40478d9e.png)

**Comment by Rasgnarok** [comment]
Forwarded!

**Comment by Rasgnarok** [comment]
https://www.pixelmonmod.com/tracker.php?p=2&t=13424
