### ISSUE TITLE
Broadcast suggestion for rules reminder

### ISSUE THREAD

**Issue by JettisonedGames** [ObliqueNET/Stratos#117]
We should really have something in our announcer for a reminder to check /rules.  Users who will sometimes skip the main floating text at spawn usually watch chat and will possibly check it.  A one that I have been using to broadcast is: Friendly reminder to everyone: Check out our /rules! They will greatly improve your experience here on Oblique.
This one could be used, or another staff member could make one.

**Comment by Rasgnarok** [comment]
`&8[&a&lInfo&r&8] &dUse /rules for a list of guidelines, user commands and helpful tips to play on Stratos!` is now live on Stratos (and Terra too)!
