### ISSUE TITLE
Pokedex pictures aren't scaled properly.

### ISSUE THREAD

**Issue by Forensiic** [ObliqueNET/Stratos#122]
I've noticed that a few of the pictures are either too big for the pokedex or are out of the frame entirely.
![2019-02-28_16 00 58](https://user-images.githubusercontent.com/47290518/53607107-34396d00-3b72-11e9-98f5-1ae54ef763cb.png)
![2019-02-28_16 00 23](https://user-images.githubusercontent.com/47290518/53607108-34d20380-3b72-11e9-96cf-ec386bd43bd8.png)
![2019-02-28_16 00 27](https://user-images.githubusercontent.com/47290518/53607109-34d20380-3b72-11e9-8212-1ba843df2c0e.png)
![2019-02-28_16 00 42](https://user-images.githubusercontent.com/47290518/53607110-34d20380-3b72-11e9-92db-3eb718b6edaf.png)
![2019-02-28_16 00 47](https://user-images.githubusercontent.com/47290518/53607111-34d20380-3b72-11e9-98a5-c0210fef542d.png)
![2019-02-28_16 00 52](https://user-images.githubusercontent.com/47290518/53607113-34d20380-3b72-11e9-8568-8a3ed8ecdfc5.png)

**Comment by Rasgnarok** [comment]
Please report directly to the mod: https://pixelmonmod.com/tracker.php?p=2
