### ISSUE TITLE
Staff

### ISSUE THREAD

**Issue by KlanfyDare** [ObliqueNET/Stratos#124]
Staff are oke when they see someone selling stuff for overpaid price, as that can be considered as SCAM.
And when someone says something to person who is selling overpaid price they get told not to , but guy who was seling stuff gets away with it

**Comment by fatyg5** [comment]
No, it's not. If you walk into Walmart and pay $300 for a candle and then find it on Amazon for $2, you were not "scammed", you made a dumb decision. Our staff aren't there to be your accountant. Please don't make tickets for stuff like this.
