### ISSUE TITLE
Banned For Alts

### ISSUE THREAD

**Issue by ShockedOwl** [ObliqueNET/Stratos#125]
My IGN is ShockedOwl and I was recently banned for using alts to increase my chances of getting a legend. I understand completely why it was wrong and why I was banned for it. It is never my intention to cause trouble on any server that I play on and I apologize because I did just that. If you could forgive me this one time I assure you that I will not cause any more unrest on the server and you can leave my alts banned.

**Comment by fatyg5** [comment]
Your account will be unbanned in one day from now, as a small punishment. Your alts, however, will stay banned, and we expect that you will not use anymore.
