### ISSUE TITLE
out of date wiki(list)

### ISSUE THREAD

**Issue by deathybankai** [ObliqueNET/Stratos#127]
Submitted by deathybankai

This is a list of items i have found on the wiki that dose not mach what is ingame on the Stratos server as of 3/11/2019.

If any clarification on anything is need feel free to comment! 

Ras said i could keep going..... so i did :D 
Sorry for the extra work!

### -Shops
https://github.com/ObliqueNET/Stratos/wiki/Shops

**Item -Wiki Price- InGame Price**

**General Shop -**
Rare candy-1000-500

**Luxury Shop-**

1. Glowstone - 200-150
2. Sea Lantern - 200-150
3. Nether Rack - 100-50
4. Nether Brick - 100-50
5. Red Nether Brick - 100-50
6. Nether Wart Block - 100-50
7. End Stone - 200-100(not in same order in the shop as in wiki like other items)
8. Soul Sand - 100-50
9. Purpur - 200-100
10. End Rod - 200-150
11. Mushroom Stem - 200-Not In Shop
12. XP Bottle - 50- Not In Shop

**TM Shop-**

1. TM01 Dragon Claw - 5000-7500
2. TM17 Protect - 7500-5000
3. TM171 Aurora Veil - Missing-3000 
4. TM172 Brutal Swing - Missing -3000
5. TM173 Smart Strike - Missing-3000
6. TM174 Leech Life - Missing- 7500

**Berry Shop-**

1. Not on wiki at all

### -Loot Crates
https://github.com/ObliqueNET/Stratos/wiki/Loot-Crates

**In All Crates-**
1. Missing item amounts from preview 
2. Xx Iron Ingot- Shown in wiki - Not shown in crate preview
3. Xx Gold Ingot- Shown in wiki - Not shown in crate preview
4. Xx Diamonds- Shown in wiki - Not shown in crate preview
5. Missing individual fossils from preview

**Vote Crate-**

1. Can not see drops in game. Gives "You do not have permission to preview this crate."

**Iron Crate-**
1. ?x Good Rod- Missing from wiki - Shown in crate preview
2. ?x A Package of Choice Items - Missing from wiki - Shown in crate preview

**Gold Crate-**

1. 1x Unbreaking 3 Enchantment- preview in games says level 2
2. 1x Efficiency 5 Enchantment- preview in games says level 3
3. 1x Feather Falling 4 Enchantment- Shown in wiki - Not shown in crate preview
4. ?x Super Rod- Missing from wiki - Shown in crate preview
5. ?X Ice Stone- Missing from wiki - Shown in crate preview
6. ?x Cake- Missing from wiki - Shown in crate preview
7. ?x Creeper Head- Missing from wiki - Shown in crate preview

**Diamond Crate-** 

1. ?x A Suit of (All Evolution Stone Armor) Packets- Missing from wiki - Shown in crate preview
2. 1x Depth Strider 3 Enchantment-  Shown in wiki - Not shown in crate preview
3. ?x TimeSpace Altar- Missing from wiki - Shown in crate preview
4. ?x Static Shrine- Missing from wiki - Shown in crate preview
5. ?x Frozen Shrine-Missing from wiki - Shown in crate preview
6. ?x Fiery Shrine-Missing from wiki - Shown in crate preview
7. ?x Creeper Head- Missing from wiki - Shown in crate preview
8. ?x Bottle o' Enchanting- Missing from wiki - Shown in crate preview
9. ?x Super Rod- Missing from wiki - Shown in crate preview

**Heads Crate-**
1. No easy way for me to check this

**Store Crate-**
1. Has no preview

### -Move Tutors
https://github.com/ObliqueNET/Stratos/wiki/Move-Tutors

**Ground Tutor-**
1. Fire Punch - 3 Soul Badges- Shows no charge in game

### -Player Commands
https://github.com/ObliqueNET/Stratos/wiki/Player-Commands

**Suggestions-** 
1. Mention that a lot of the commands bring up a clickable menu in chat

**Features-**

1. /ctb - Shown in wiki - dose not work in game

### -Money Making 101
https://github.com/ObliqueNET/Stratos/wiki/Money-Making-101

**Pokemon Drop Pricing-**
1. Blaze Powder - 5 - Not sell able
2. Blaze Rod - 20 - Not sell able
3. Do not have the means to check other items

**Poke Loot-**
1. Do not have the means to check this

**Comment by PharaohMo** [comment]
Good work on this!!

**Comment by InsaneModee** [comment]
Helpful! But outdated but nice!

**Comment by Forensiic** [comment]
> Helpful! But outdated but nice!

The post was meant to outline outdated information.

**Comment by deathybankai** [comment]
> Helpful! But outdated but nice!

Thank you for the comment!
I have added some text to make the intention of this list more clear!

**Comment by Vohras2** [comment]
Thanks for this. I think you'll find most of this is updated now, outside the berry shop being added. I'll get around to that soon.
