### ISSUE TITLE
ghandi_123 aka AsapRocki

### ISSUE THREAD

**Issue by GangGanggg** [ObliqueNET/Stratos#128]
Past Username : ghandi_123
Current Username : AsapRocki
I was greeted with this msg today. I am a new player who just wanted to find a mega boss so I made the stupid decision to use alts to afk for them. This might be stupid but I also spoke to a mod and found out that pokeradar was blacklisted too so I have gone ahead and removed that as well. If anything is possible to get my IP unbanned, I will promise not to do it again. 
![2019-03-11_19 22 54](https://user-images.githubusercontent.com/48231159/54171388-5f0ba700-4437-11e9-8007-570aed507c9a.png)

**Comment by InsaneModee** [comment]
Any alt boosting is against the rules which is unfair just for finding a mega boss which you can easily find in the wild (Just Saying)

**Comment by Rasgnarok** [comment]
Can you please input your username? I need that information to complete the ban appeal.

**Comment by GangGanggg** [comment]
Yes my username when I got banned was ghandi_123 but I recently changed it to AsapRocki.

**Comment by Rasgnarok** [comment]
Ok, thanks, I'll forward to @MrBritish8

**Comment by GangGanggg** [comment]
Any updates ?

**Comment by fatyg5** [comment]
You are unbanned. If you are caught breaking anymore rules, you will be rebanned permanently. Due to your use of alts, your IP has been limited to only one account, so choose wisely.
