### ISSUE TITLE
Unban?

### ISSUE THREAD

**Issue by W4nkey** [ObliqueNET/Stratos#129]
I just got banned for "Racial Slurs" which is not the case. I never said anything Racist to anyone. I'd like to be unbanned because I worked hard for what i had in that game and it is unfair to have all of it be lost because of miscomunication.

**Comment by W4nkey** [comment]
And just saying its not even just the server. I made friends on it and I would really hate to not b able to play with them anymore. Its a great community and i would be really sad to not be a part of it anymore

**Comment by InsaneModee** [comment]
Saying the n word to anyone is unallowable and can hurt someone feelings or feel offended by the that word. Although you did say the N word in messages and public chat it still is not acceptable.

**Comment by lolanonymous** [comment]
You have been unbanned, but let it be known we do not take kindly to those words here, in any context.

-Hrej
