### ISSUE TITLE
Fossil cleaners only work for 3/11 covered fossils.

### ISSUE THREAD

**Issue by Forensiic** [ObliqueNET/Stratos#130]
Only the Claw, Skull and Armor covered fossils actually "clean" after going through a Fossil Cleaner. The other 8 give back the same covered fossil.

https://www.youtube.com/watch?v=nEI7WhHnNpc

**Comment by SammyL2002** [comment]
I'm pretty sure all the fossils work it's just a visual glitch. Someone was having some problems a few days ago with it. Currently of you want to see if they are actually ready then relog and if they are they won't be spinning but if they are not ready then they'll carry on. I was testing this and it worked with amorous fossil (or whatever it is) and it worked do it is not fossil specific

**Comment by Rasgnarok** [comment]
I need this reported to Pixelmon directly: https://pixelmonmod.com/tracker.php?p=2
