### ISSUE TITLE
Unban Request

### ISSUE THREAD

**Issue by minidrones** [ObliqueNET/Stratos#131]
So i started playing the server yesterday with my friend. We were proud of what we had achieved and all but we both got bored of waiting for our apercorn to grow and our Mechanical Anvil to work so we both opened up a one of out alt accounts so all of this would grow and work better while we were out in the world searching for and training our Pokemon. Then out of nowhere we both got banned for "Using Alts for legend spawns" on both of our accounts. We had no idea that was even a thing much less that doing such would result in a ban. We were just 2 lazy people who didn't want to afk our main accounts for a long time so we could have pokeballs. My main in-game name is Minidrones and my alt is McCarter_111 . My friends main in-game name is Xxaxxourre and his alt is Albino_Applle. We will stop using the alts we just would have liked to at least gotten a warning or something when we are both so new to a server and we were both interested in buying a rank...

**Comment by fatyg5** [comment]
Your IP reports 6 accounts, but you claim to have only used 4 accounts. This means you were using more alternate accounts than just the ones you said. Why is this?

**Comment by minidrones** [comment]
We live together, so that could be part of it. could you name the other 2 accounts and i could tell you if I have herd of them?

**Comment by minidrones** [comment]
Still we were both new to the server and even a warning or a temp ban would have been nicer or just something to let us know that we were breaking the rules idk

**Comment by MrBritish8** [comment]
We will pardoned the accounts "Minidrones" and "Xxaxxourra" only. so you can continue to play without ults. but that this as a major warning if your caught using ults you will be banned again.
