### ISSUE TITLE
banned appeal/misunderstood

### ISSUE THREAD

**Issue by afformative** [ObliqueNET/Stratos#132]
I was temp banned 3/19 for a day for "boosting" my town, i do have one alt account in there, the other account was my brothers and they both got perm banned. I normally ride solo when i play faction type servers so i had my alt acc load my furnaces while i was out so i could keep cooking/smelting. I wasn't trying to boost my town or anything, i could care less about that lol. Also would like to see if my brother account, ColoursOG could get unbanned, if my alt StylezOG stays banned i dont mind. Thank you.

**Comment by afformative** [comment]
Also it stated for "Vote Boosting" when honestly i just thought i was helping the server out, if you want to wipe the /bal on StylezOG and ColoursOG that's fine too.

**Comment by afformative** [comment]
<3

**Comment by fatyg5** [comment]
Your brother will be unbanned. Do not use alts anymore, it's clearly in the rules.
