### ISSUE TITLE
accountlink issue

### ISSUE THREAD

**Issue by Trouterfly** [ObliqueNET/Stratos#133]
Hello.

I am unable to purchase things on the Stratos Market in discord.  This started after I changed my username on Mojang's wetbsite.  I was told to make sure my account was linked.  Bots said it was when I did the !link command by telling me my account was already linked.  Then they asked me to unlink and relink.  When I used the !unlink command, it said I didn't have an account linked.

Would very much appreciate your help on this issue.  

Thanks in advance!

**Comment by Rasgnarok** [comment]
@Hiroku Any way I can see what account was linked, or force unlink?

**Comment by fatyg5** [comment]
Believe this was dealt with, I'll leave it open for a few days, but something was being typed incorrectly. After checking his linked account he used the unlink properly.
