### ISSUE TITLE
Ban Appeal-Completely Misunderstood

### ISSUE THREAD

**Issue by GhostWalker777** [ObliqueNET/Stratos#134]
IGN:GhostWalker777
Server:Stratos
Date:3/19/2019 at like 7:40
Issue: Basically I was hunting for the second to last Pokemon for my hyper aggro team I had just drafted.I was in discord with a few friends and we're chatting and the discussion of our old Faction server comes back up. Now my friend Dru is completely toxic on Factions and so he said he was blacklisted and I asked "Why?" and hes like "idk they just said I'm blacklisted" and I followed up by doing /t chat to enable team chat and then I asked him are you sure it's not for saying "Nigger" which I typed out(Because saying words like those are forbidden in my house)  and I got auto banned. I'd just like to apologize and see if there's anyway I could get unbanned for this since as a Faction we're doing a Red v Blue team event and right now is the prep time and I'm completely behind. I realize that saying derogatory terms like the stated above are completely wrong and I acknowledge that, I'm just hoping you can forgive me for my mistakes.
-Ghost

**Comment by fatyg5** [comment]
There is no misunderstanding. You typed a derogatory word into a Minecraft chat, town chat, or not, it should never be said. Morally, saying something like that, without having context to say it, should be recognized as shameful. Either way, your account will be unbanned, but if you are caught saying anything like this again, the ban will be permanent.
