### ISSUE TITLE
I apologize for acting childish

### ISSUE THREAD

**Issue by dahruu** [ObliqueNET/Stratos#136]
Hey man, extremely sorry i was acting childish. here’s a few things.
 1). I lied because i was distressed after being banned because I actually enjoyed playing the server and didn’t want to be banned.  I was afraid you wouldn’t unban me since I had evaded the ban rather than appeal the ban.
2). I was on the  previous day and said “nigger” in town chat and I didn’t know it wasn’t allowed. Before you say it’s not a word to use outside of a certain context, I am aware of this, and whilst it does not reduce the severity of the term, I played HCF for 4 years before going to mod packs and it sometimes causes lapses of judgement leading to toxic statements such as previously mentioned.
I really enjoy playing the server. Despite my previous actions, both in-game and on discord, I do understand my lack of judgement and maturity in this, and for what it's worth at this point, I'm truly sorry. Thanks in advance for taking the time to read this,
-Pro

**Comment by fatyg5** [comment]
You say right in number 2 that you were indeed ban evading. For this, you're not being unbanned.
