### ISSUE TITLE
After a whole day my town deleted

### ISSUE THREAD

**Issue by Akemi15** [ObliqueNET/Stratos#14]
Yesterday I wasn't on the server all the day but in the weekend I was on the server searching and making my town with a friend. Today when I entered, my poke kit was missing, just the pokeballs, the cookies and the potion were there...I quite don't remember if the poke kit contained something else but I can assure you that my chest was a bit more empty than the last Sunday....it can be resolved?...oh yeah i forgot to mention that my PC(red) from the poke kit is missing too

**Comment by Rasgnarok** [comment]
Closing, please open a new ticket if the issue happens again.
