### ISSUE TITLE
doompkin bugg q.q

### ISSUE THREAD

**Issue by anlokaneki** [ObliqueNET/Stratos#140]
sooo i got the doompkin curse  on  binding from a vote chest  i think  or from  a merchant i dont remember but im  new and dindt know  what this i s  .. so i  equip  it and now  i  cant  get it  off sadly q.q and my name is anlokaneki in the game

**Comment by Lonetus** [comment]
I'm Not Admin, im not a mod. But i might have help for you if you log in to game : ) -Lonetus

**Comment by Lonetus** [comment]
https://minecraft.curseforge.com/projects/no-pumpkin-blur

**Comment by Lonetus** [comment]
Before admin can fix you
