### ISSUE TITLE
Scizors lost. 

### ISSUE THREAD

**Issue by Corn1123** [ObliqueNET/Stratos#146]
I just lost my scizor. It was level 35 with Giga impact false swipe fury cutter and agility. It also was around 75% IVS. I lost it by putting it in my box and then I went to get it out and it wasn't there. Proof that I have it is that I have battled the electric gym many times with it. My IGN is Corn1123.

**Comment by Rasgnarok** [comment]
Apologies for the delay in answering, a moderator will get to this soon.

**Comment by CenizaRey** [comment]
Hiya! Sorry for the delay, I'll get to that as soon as you're next online. DM or ping CenizaRey#4375 on the Discord next time you're online, and I'll jump on to give you your Scizor.

**Comment by MrBritish8** [comment]
was this dealt with?

**Comment by JettisonedGames** [comment]
I have the scizor ready to be returned with the information that was given.  Just ping me on discord when you are ready for it to be returned, and I can get it to you as soon as possible.  My discord tag is The Trash Man#5786, or you can ping me out in #stratos-support or #chatbox with @JettisonedGames.
