### ISSUE TITLE
Claim/Town Removal

### ISSUE THREAD

**Issue by Inheritor55** [ObliqueNET/Stratos#147]
A town is known as "Undertale" has been afk for over 100 days and is directly next to our town "Arctic Rise", Please remove their claims.

**Comment by JettisonedGames** [comment]
@Hiroku , there seems to be an issue with autodeletion of towns once a user has been gone for a certain amount of days.  I know of at least 2 other towns in the same boat and can provide if needed.

**Comment by Hiroku** [comment]
I'm aware of it; Sponge screwed me over and I need to make further changes to bypass Sponge's inane changes.

**Comment by fatyg5** [comment]
Removed. I'll make a ticket for Hiro that can be closed when he fixes this permanently.
