### ISSUE TITLE
Town Removal Request

### ISSUE THREAD

**Issue by Meokuba** [ObliqueNET/Stratos#149]
There are two towns in the mountain range I was hoping to flatten that have both been abandoned, was wondering if I could get them removed to finish doing so.
<img width="347" alt="2019-04-06_16 24 10" src="https://user-images.githubusercontent.com/49353665/55768271-17297100-5a31-11e9-998e-cbbf97bd1168.png">
<img width="476" alt="2019-04-06_16 24 03" src="https://user-images.githubusercontent.com/49353665/55768275-1a246180-5a31-11e9-8342-eebf530d4d7e.png">
<img width="353" alt="2019-04-08_16 48 58" src="https://user-images.githubusercontent.com/49353665/55768282-21e40600-5a31-11e9-838a-6bb5f000c9a8.png">
<img width="481" alt="2019-04-08_16 48 18" src="https://user-images.githubusercontent.com/49353665/55768283-21e40600-5a31-11e9-8b08-7d7068f2dfac.png">

**Comment by fatyg5** [comment]
Done.
