### ISSUE TITLE
Sugar cane in spawn throws lots of "you do not have permission messages"

### ISSUE THREAD

**Issue by JettisonedGames** [ObliqueNET/Stratos#15]
The sugar cane in spawn (tested in 2 different patches) just fills chat completely full of "You do not have permission in admin" messages.
https://cdn.discordapp.com/attachments/481684797874372623/522128582835830785/unknown.png

**Comment by Rasgnarok** [comment]
Does this still happen?

**Comment by fatyg5** [comment]
Fixed.
