### ISSUE TITLE
Don't recieve blocks after breaking stone, wood, coal, ect.. 

### ISSUE THREAD

**Issue by MrShotty** [ObliqueNET/Stratos#150]
Hey, I've been playing on the Terra server on and off for probably around 2 years now. After hearing about the upcoming wipe, I decided to play some pixelmon again so I jumped on the Stratos server for first time. After rtping, I immediately noticed that I was not getting any blocks from wood, stone, or coal. I tried mining them with different pickaxes/axes, deleting and reinstalling the mod pack, and killing myself. None of which worked. For some reason, I can mine dirt and sand just fine. Also, mining things works fine for me in singleplayer and terra.

Another thing is that every time I catch a pokemon I get stuck in waiting.

Many people tried helping me with the problem but no one understands my issue.    psycho_sinner suggested that the server config for my character probably went bonkers for some reason. I'm not against it being deleted since I just joined Stratos.

Anyways, I hope you guys can fix the problem. Thanks for your time!

IGN: Mr_Shotty

**Comment by Hiroku** [comment]
This was an issue inside the RPG plugin. Specifically for players who had never received any experience in Mining or Woodcutting. It's resolved since last restart - sorry for the issue, Mr Shotty.
