### ISSUE TITLE
Town Removal / claim

### ISSUE THREAD

**Issue by Nicokou** [ObliqueNET/Stratos#151]
Yo i'm Nicokou and i have this 1 chunk claim on my island that's really bugging me from a random player that hasnt been online for like 31/32 days. 
Guy's town
https://gyazo.com/ee09ba10bd2b4d3da02eec9824deaf65
His claim
https://gyazo.com/e6f014c589a42fd220e2f11e230900fc
Coords in his claim
https://gyazo.com/3d53d350cbf99599deb9a3dd91157f74

**Comment by fatyg5** [comment]
Done.
