### ISSUE TITLE
cant tp back to town

### ISSUE THREAD

**Issue by strikersbaseball** [ObliqueNET/Stratos#152]
me and my friend cant tp back to our town and when we do /town it says we arent in a town but when we type a message it shows our town name still next to our name. town name=coolkidsrus
my ign= strikersbaseball
friend ign= coolkidsrus (same as town)

**Comment by fatyg5** [comment]
I'm unable to find your town, so I assume you are new players. Any idea where it could be? We had an issue where a lot of data was lost, I had backups, but your town wasn't in it, so it must be a newer town.
