### ISSUE TITLE
Town's still not auto disbanding

### ISSUE THREAD

**Issue by fatyg5** [ObliqueNET/Stratos#154]
Just opening this so we have an area to make sure this is updated and tested when hopefully fixed.

**Comment by Hiroku** [comment]
This should now be fixed, and saw towns being disbanded for 20 weeks of inactivity. Need to know if there are any further cases of towns failing to disband.

**Comment by fatyg5** [comment]
I have seen errors recently in startup logs regarding this. Would you like me to find them?

**Comment by Hiroku** [comment]
Yes please
