### ISSUE TITLE
Town no longer exists?

### ISSUE THREAD

**Issue by Toponith** [ObliqueNET/Stratos#156]
I also lost my town. When using command /town it says I am not in a town although when I chat it shows my town's prefix. I know where my town is but it is all unclaimed which caused me to get robbed. I have spent in-game money for my town to get more claims that I do not wish to be lost. Please help me fix this issue.
IGN: Toponith
Town Name: Belladonnas Garden

**Comment by Forensiic** [comment]
Had this been handled yet?

**Comment by Toponith** [comment]
Yes both Faty and Aether have helped me regain my claims and items stolen
Thanks everyone

**Comment by Forensiic** [comment]
Good to hear. If you could close the thread, it would be appreciated.
