### ISSUE TITLE
can i be Unbanned?

### ISSUE THREAD

**Issue by JeromeJap** [ObliqueNET/Stratos#158]
Hey There, I wanted to ask if you can unbanned me..
i was banned because of Stealing from unclaimed Builds.
And i have to be True, i didnt read the rules and thought it is ok, if it isnt claimed. :/

Sorry for That. :/

sorry for my English.! :D

**Comment by fatyg5** [comment]
"I didn't read the rules"

Why didn't you read our rules, that tell you not to do those things? Clearly you knew the rules existed, since you said you didn't read them, and you chose not to read them.

**Comment by JeromeJap** [comment]
Thats true. It was wrong From me. but directly Ban? I think its a little bit hard. 

Sorry for that mistake.

**Comment by JeromeJap** [comment]
? :/

**Comment by MrBritish8** [comment]
Due to the amount of item that you stole. you will not be pardoned as it is against the rules and the reason "i didn't read the rules" doesn't make it fine.
