### ISSUE TITLE
Custom roles in towns

### ISSUE THREAD

**Issue by JettisonedGames** [ObliqueNET/Stratos#16]
Add a possible way to assign custom roles in a town using existing positions.  Simply put, you can give certain people tiles, such as: Treasurer, builder, ambassador, etc.  These would add an extra layer of realism and community to the town, as if you need assistance with a specific thing, you can refer to the actual person who may be in charge of that specific thing.

**Comment by Rasgnarok** [comment]
Closing this one in favour of the new one. Let's streamline discussion!
