### ISSUE TITLE
Lost my Hakomo-o

### ISSUE THREAD

**Issue by MiddagY** [ObliqueNET/Stratos#161]
Around 3-3:30 pst, i lost my Hakomo-o. I dont know the exact time, but i do know that it happened after I nicked it to Haka-momo. Hawky looked in my pc to double check that it was actually missing. I have pictures as proof of ownership of said hakomo-o.
![2019-04-13_16 01 49 png 2](https://user-images.githubusercontent.com/49600638/56086896-06a03e80-5e15-11e9-9d31-980b9c414bc9.png)
![2019-04-13_16 01 52 png 2](https://user-images.githubusercontent.com/49600638/56086898-099b2f00-5e15-11e9-9292-05f09b8116a2.png)

**Comment by Forensiic** [comment]
Do you recall what the IV's were?

**Comment by MiddagY** [comment]
They were 33% I know that. But I don't recall the exact ones

**Comment by Forensiic** [comment]
Ping me on discord when you are online next. @Forensiic
