### ISSUE TITLE
is there any way i can get my shulker box back from clearlag? it ate it.

### ISSUE THREAD

**Issue by plueytg** [ObliqueNET/Stratos#162]
was picking up shulker box and cleartag rekd it.

**Comment by Forensiic** [comment]
Do you remember the contents?

**Comment by plueytg** [comment]
the only thing i remember is 2 exp alls the rest was just random loot from pokeballs

**Comment by Forensiic** [comment]
What is your IGN?

**Comment by plueytg** [comment]
Plues
