### ISSUE TITLE
Discord Unban Request

### ISSUE THREAD

**Issue by smalm77** [ObliqueNET/Stratos#165]
My Discord username is 'smalm'. I got banned on the servers Discord a bit over a week ago after I had posted multiple photos of McJuggerNuggets, a popular YouTuber if you didn't already know. I posted about 7 or so pictures in total over different chatrooms. I did it as an inside joke that me and my friends have, without really thinking. I didn't think it would faze anyone in the Discord, I was just fussing around. I regret that I did it and want to apologize to anyone I disrupted, and I wish to be unbanned. In the future I will obey the rules and not spam.

**Comment by fatyg5** [comment]
No, you will not be unbanned. After a staff member spoke to you, you decided to send more unwanted pictures to that staff member. You also told my staff member, when you asked why you were banned from Discord in game, and I quote "You guys are just babies you dick". Enjoy your permanent ban from the Oblique network.

**Comment by MKFusion** [comment]
My discord name is Biatrixx#5752 and i got banned(i think) by sending Unepropriate pictures (im not realy sure) and at the time i didnt think discoud server would affect that much, for talking with staff members and make some trades with other people. im realy sorry and i wont do it aggain
