### ISSUE TITLE
Unban Request

### ISSUE THREAD

**Issue by Murray823** [ObliqueNET/Stratos#167]
I will admit to giving the other player my party for the gym ,but I didn't realize that it was a offense reasonable of a ban and there was no warning so it seems that I should've at least  had a warning then if attempted again then banned. If the unban is not granted I would like the pokemon traded to return to my PC

**Comment by MrBritish8** [comment]
Your ban is only a 2 day Temp ban so u can wait for the ban to run out. As for Giving a player your team it is stated in the rules for the gyms. rule no.6 "No sharing teams, no team building for others. Tips are OK."
So once your ban is up you will have to get the team back from the player u gifted it to.
