### ISSUE TITLE
Unban Request

### ISSUE THREAD

**Issue by smalm77** [ObliqueNET/Stratos#168]
Reason: Perm Banned for Racism, Spam and Disrespect toward staff members.

I can begin with the racism part. After having to wait for over a week to get help from a mod about my Discord ban I get told that I have to appeal my ban, and I'm sorry but that was just BS. My friend (jotha9) had talked to Juuzou, who I believe is the guy who banned me, and he had said that it would only be a 24h ban. So after I got the sudden news that I had to write an appeal, which is really annoying, I just went on a small rampage posting two meme photos and commenting "Nice work ethic" (not very offensive I would say) after Grassi had said "Lmao k then less work for me". One of those pictures just so happened to be a photo of a Swedish chef with a pre-nazi swastika on his forehead and in the background. It was at the top of my Pictures folder and I just thought it looked funny, I don't support racism or nazism in any way. Also I don't see how me sending that picture to a mod on Discord would disturb the entire Oblique network. I'm sorry if it did offend Grassi though. It was 2 in the morning, I was really tired and me and my friends were just fussing around not really thinking I would get a PERMANENT ban from it. Though I have to say it was still wrong of me to do what I did, I regret what & take full responsibility for it and I would never do it again. 

Now to the spam part. If you mean that I've spammed in Discord, as I've said in my previous issue I'm deeply sorry for that and I could bring up excuses like me being bored or whatever but that still doesn't make it right. That I later sent two pictures to Grassi isn't spam though, we had legitemately talked. And also I wanna address what Faty said in my previous issue, "You guys are just babies you dick", I have no idea where that came from and I have honestly never said that. You must have mistaken someone else for me. That I would take responsibility for if I'd actually say that. Also I can admit that I've semi-spammed in the MC chat at times, like sending letters from the Swedish alphabet in caps and so on. If it annoyed someone or just ruined the chatbox, I will never do it again.

I can agree that I have been a dick to some staff members. For example I've said "stfu" to Sahvkriinov a couple of times (in a jokingly way, she also always just sits silent so it was just for the fun between me and my friends), dissed staff during unexpected restarts, complained about legendary spawns etc. I want to apologize to any staff member that I pressed down on or dissed. Things can get very hysterical at times and you don't really realize that you're doing something wrong. So sorry about that, I really regret it. But at the same time it's not like you guys are higher standing beings than us. Just because I criticise someone doesn't mean I should be banned, that's my freedom of speech. At the same time I can agree I might have been too harsh at some points.

All in all, I'm very sorry for all the problems I've caused and I just want to have a nice time playing Pixelmon with my friends. If you decide to revert the permanent ban, I would be very thankful, but you don't have to completely unban me instantly. You can still ban me for a week or for a month or whatever you wish, I will learn my lesson.

**Comment by fatyg5** [comment]
This unban request is too little too late. Your first ban from our Discord was for the fact that you spammed a random picture in our server's chat at least 10+ times, and were banned because I for sure was not removing your idiotic posts, so I let Discord auto-delete them. Furthermore, the fact that you defend yourself for sending our staff member a disturbing picture of a dude with a Nazi symbol on his head says enough for me to not unban you. You seem to have no control over yourself and what you do, as you know you were already banned from our Discord, then got angry and continued to act childish in the DMs of our staff member and because of that, I don't think I fully trust anything said here. For that, you won't be unbanned at all.

**Comment by Rasgnarok** [comment]
>at the same time it's not like you guys are higher standing beings than us
It's a private server, I pay for it, I decide the rules.
>that's my freedom of speech
Where? In the US? In Canada? It's the internet friend, I decide what your freedom of speech is.

As Faty said, and as I have replied to your DMs, no, you aren't getting unbanned. Learn some manners o/
