### ISSUE TITLE
Please read

### ISSUE THREAD

**Issue by smalm123** [ObliqueNET/Stratos#169]
https://gyazo.com/f870b293730e7a98be7af80889095e77

Got inside information that the dude had typed /tpa then followed by the N word. Pretty sure it was that or it was just another racist remark, doesn't really matter though does it.
This is literally the exact same thing that I got perma banned for. He makes a joke about slavery, doesn't apologize and instantly gets unbanned. I make a joke about nazism, apologize, permanent IP ban. It was pretty obvious in your response that the only thing you guys were really fazed by was that nazi picture aswell.
I'm not trying to irritate any of you or make you look like fools, it just isn't fair. And no I'm not defending myself, all I did in my last post was apologize but still spit the facts there was to be spat.

**Comment by lolanonymous** [comment]
We've already denied your appeal, please stop creating accounts and posting to our github
