### ISSUE TITLE
Unban Request

### ISSUE THREAD

**Issue by Fuklz** [ObliqueNET/Stratos#173]
Discord: Pupa#8129
IGN: Fuklz
Banned For: Toxicity

I would like to play again and return to being a Rock Gym Leader. I know to be a gym leader again is reaching at best, but I would like to contribute something to the server that is fun and dutiful, giving me reason to be on more. I found being a Rock Gym Leader to be one of the most enjoyable things to do as I became more seasoned with the server.

In the past, I was very rude to several people as a staff member, made many uncalled for and erroneous assumptions, and failed to respect senior members of the server. I understand now that my actions demeaned the entirety of staff on Oblique and damaged the quality of the server in the eyes of many players.

In my actions as a player, I was overly advantage-seeking and I attempted to take advantage of the economy of the server by breeding as much as possible, and trading as much as possible. In new gameplay I have absolutely no plans to invest as much time as I previously did into seeking the best ways to earn money on the server.

I have multiple friends- despite my actions, still playing on Oblique, and much time invested into my character on the server itself, so I hope you will let me play again.

**Comment by fatyg5** [comment]
It should be quite obvious that you won't be unbanned, but in case you were wondering, I'll elaborate.

While initially staff, there were a lot of problems in the staff team, specifically arguments between staff members and you. While I won't say who was in the right or wrong during those arguments, it's quite obvious something was happening that kept dragging you into the issues.

After a while, it came to the attention of the staff team that it many rumors were being around about staff members, which stemmed from you. Not only did this cause a massive divide in our staff team over the months that you were a staff member, it also lowered our staff's overall morale.

Your past actions were quite manipulative and not something we want on Oblique. There was always an issue with a staff member you didn't appreciate or like and it got sent to my DMs, or others, when they relatively did something minor. The only thing I can say in the end is that our staff team has improved greatly after this, and we've improved our recruiting tactics following it. The admin team had a small discussion regarding this post and feel that, the extent of your actions, can't be undone. For that reason, you will stay banned.

**Comment by Fuklz** [comment]
"While I won't say who was in the right or wrong during those arguments, it's quite obvious something was happening that kept dragging you into the issues."

I went out of my way and reported things or made claims, and the majority of them were correct. To say that the claims may be nitpicking is one thing, it's another to say that there is a problem with seeking problems.

"After a while, it came to the attention of the staff team that it many rumors were being around about staff members, which stemmed from you."

Could you tell me what these rumors were? I made several suggestions and comments in the past about various staffing positions, both negative and positive, and they were always my personal account of what occurred, with no impetus.

"There was always an issue with a staff member you didn't appreciate or like and it got sent to my DMs, or others, when they relatively did something minor."

Every single time except one, it was about the rules themselves, not staff. The fact that I had to go and message Ras on several different occasions is the only way rules could be changed to be more sensible. On top of this, any time I messaged you on subjects like that you literally just did not respond at all. I have proof of that.

"The admin team had a small discussion regarding this post and feel that, **the extent of your actions, can't be undone.**"

My actions, as in interactions with staff, can't be undone? I've legitimately left for months and thought about my problems in association with the server and have gotten over them and am now trying to be kinder. I've gone heavily out of my way to attempt to make amends with players who I know I've offended. I'm just asking you to analyze this vicariously: what have I done besides attempt to tackle problems only to be left with backlash in the majority of them? If I fail to suggest things that may improve the server, I don't feel like I'm doing things correctly.
