### ISSUE TITLE
Timers for Wondertrade/TMTrade/Megastone trade.

### ISSUE THREAD

**Issue by Soxiel** [ObliqueNET/Stratos#174]
Timers for Wondertrade/TMTrade/Megastone trade similar to the egg timers.

**Comment by fatyg5** [comment]
Yeah, I'm not sure what this is. Egg timers are random, based off of the Pokemon hatching, so no clue what that means. If you're suggesting we lower the time, we're not changing the timers of any of those plugins, it's a high timer for a reason.
