### ISSUE TITLE
Ban Appeal (WishingMagic) 

### ISSUE THREAD

**Issue by WishingMagic** [ObliqueNET/Stratos#176]
IGN: WishingMagic

About two months ago I was banned from the server for alting. I was using the alts to afk my furnaces and apricorns while I was exploring / catching pokes. I really enjoyed the server and would appreciate if I could be given a second chance somehow. I understand that I was using something to my advantage and I sincerely apologize for it. Thank you for reading.

**Comment by fatyg5** [comment]
Yeah, no. I would consider this ban appeal if it was only a few alts or just one. Your IP had over 2 pages of alternate accounts. Obviously they were being used for more than you say and you won't be unbanned for this reason.
