### ISSUE TITLE
Request to remove claims from town "Wulf"

### ISSUE THREAD

**Issue by ZexyKun** [ObliqueNET/Stratos#177]
Hi! I ran across a 2x1 chunk claim belonging to a town named Wulf when building something next to my own town Exia. Their claims are underground, and thus I wasn't able to see/notice it until I was almost done with the outline.

I'm requesting to remove the claims, but my build won't be destroying any chests. I just need to build above their claims. Their last member was online 69 days ago (lmao) from this post, and if the members do come back, their stuff will be left untouched. Thank you!

**Comment by fatyg5** [comment]
I'll have an admin take a look and remove it if justified

**Comment by lolanonymous** [comment]
Claim disbanded and person's items removed, enjoy.
