### ISSUE TITLE
Claim lost and raided. 

### ISSUE THREAD

**Issue by ChibiDD** [ObliqueNET/Stratos#185]
I've been absent for a month and abit now and it seems in the time I was away that I somehow lost my town "Da bois". Due to that an entire chest room was looted and I few builds were griefed. 

I'm not too concerned on getting the items back as there would be too much to list off. But I would however like to see whoever is responsible atleast spoken to or punished as there was enough stuff in those chests to set anyone up for awhile and yet they still had to ruin my build to get every last drop of worth they could. 

Ign: ChibiDD 

![2019-04-25_18 35 46](https://user-images.githubusercontent.com/47016870/56722061-9933cc80-6789-11e9-8a3f-cdf5280af28a.png)

Here is the main chest area, cords are in the top left. Also in the chest room on the right wall was some shulker boxers a pc and a couple other things (Fossil machine, fossil cleaner, ect.) which I have screenshot below. 
![2019-04-25_18 35 49](https://user-images.githubusercontent.com/47016870/56722207-e9ab2a00-6789-11e9-8bd8-fc664f8c69dd.png)

Next is my dragon breeding house, they looted all the diamond/emerald blocks that I used for my breeding mat. 
![2019-04-25_18 36 02](https://user-images.githubusercontent.com/47016870/56722300-237c3080-678a-11e9-8560-6c3c1c521f70.png)

and lastly is underground, one of the rooms had a line of redstone blocks stolen. 
![2019-04-25_18 38 14](https://user-images.githubusercontent.com/47016870/56722351-41e22c00-678a-11e9-838e-f9983542fba9.png)

I know it's a big job for anyone to handle and even though it was unclaimed for maybe awhile idk, It still shouldn't have been griefed as It clearly states that even if 'Unclaimed' You still shouldn't grief in the rules. 

Thanks again, Chibi.

**Comment by Sahvkriinov** [comment]
Your Situation is currently being handled by the mod team, mind telling me your discord?

**Comment by Sahvkriinov** [comment]
The issue was taken care of all items refunded to ChibiDD

**Comment by Forensiic** [comment]
The players involved have been dealt with accordingly. The items we could find have been refunded to your inventory. If you feel you are still missing something, please message a mod in game or on discord. If you have any questions or concerns about the lost town/claim refunds feel free to ask here or in the stratos-support channel on discord.

**Comment by fatyg5** [comment]
Closing for now. If you have any other small things missing or issues, feel free to use our Discord support channel.
