### ISSUE TITLE
Add the Wing Items to /warp shop

### ISSUE THREAD

**Issue by nugsy** [ObliqueNET/Stratos#186]
The EV training "Wing" items (Health/Muscle/Resist/Genius/Clever/Swift) be made sellable to the /warp shop NPCs? They're pretty much the same items as Carbos, Zinc, etc.

**Comment by Rasgnarok** [comment]
More stuff for eco, @Vohras2 . Maybe as rewards somewhere?

**Comment by Vohras2** [comment]
I've got this on my testing list to look into for the next shop update. So just hold them for now.
