### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Qaell** [ObliqueNET/Stratos#187]
Minecraft User: Qael
I was recently banned for griefing.
I just want to state, I found the plot and did not know that unclaimed plots were considered griefing if you looked through the chests. I was not aware and I am now. I will most definitely return the clay blocks I took from the chest and I will not ever get in trouble and will not be a problem again. Most of the chests were empty when I found the plot owned by ChibiDD (I see it was his now). I am an avid builder and that's why I took them thinking they weren't being used and the plot was abandoned. Please give me a second chance, this is my first offense, and I love the server.

**Comment by fatyg5** [comment]
I'm confused, you love our server, but don't know our rules? The one that specifically states
> 4: Do not grief or steal from others, even if it is unclaimed

So you decided "Hey, I'm just going to take _everything this player ever worked on, because I need it_"?

**Comment by Qaell** [comment]
I don’t recall destroying any blocks or anything. It would be nice if you could consider bringing me back. I recently joined and haven’t been playing for too long so I wasn’t fully aware of the rules on griefing.

**Comment by Grassip** [comment]
You are unbanned. Please read all of the rules using the command /rules once you get back online. If you are caught breaking the rules again, you will be permanently rebanned.
