### ISSUE TITLE
Command /wiki [pokemon] genderratio not working

### ISSUE THREAD

**Issue by Lone6** [ObliqueNET/Stratos#189]
When the command is run for any pokemon that has a gender, there is just a blank line in the chat as shown in the screenshot. Logs show an error for this.  For pokemon with a gender, the command works as normal. 
![image](https://user-images.githubusercontent.com/50112090/56906814-f043e500-6a9a-11e9-80ec-c0d1f57a8aaf.png)

**Comment by fatyg5** [comment]
Works fine for me. Closing as most likely fixed.
