### ISSUE TITLE
can you unban my friend

### ISSUE THREAD

**Issue by bo68nito** [ObliqueNET/Stratos#190]
hello, my username in bo68nito and my friend recently got banned from the Stratos server and I beg you amazing creators to unban him from the Stratos server. his username is thiagocrod and as sad as it sounds his parents recently divorced and his birthday is in 12 days, I just want him to be happy.     thank you for the amazing game.

**Comment by Grassip** [comment]
If he wishes to be unbanned, he needs to file the ban appeal himself. Please direct him here so that he may do so.

**Comment by bo68nito** [comment]
why does he have to do it

**Comment by bo68nito** [comment]
please just do it for his birthday

**Comment by bo68nito** [comment]
i dont care, he loves pixelmon

**Comment by bo68nito** [comment]
his username is thiagocrod PLEASE!!!

**Comment by fatyg5** [comment]
Don't respond to this ticket again. Either he makes a ticket himself, or he won't be unbanned.
