### ISSUE TITLE
Please I want to get unbanned

### ISSUE THREAD

**Issue by thiagorodriguesnoni** [ObliqueNET/Stratos#192]
Dear creators 
I know I did some things that I should not have done but I regret doing this and I really want to play with both of my friends and also trying to get better at the oblique pixelmon server. the first issue was my town called an inappropriate way and also the second reason that I was spamming help me because I was very laggy and I thought I needed help I am very sorry.

**Comment by bo68nito** [comment]
please let my friend play

**Comment by Grassip** [comment]
You have already been told no once. The fact that you stated in your last appeal that you didn't know what you did shows that you truly don't have the best intentions, especially considering how utterly offensive your actions were. Do not send in another appeal, for it will result in a ban from the Github.
