### ISSUE TITLE
Infinite Water Glitch

### ISSUE THREAD

**Issue by UxerhintTV** [ObliqueNET/Stratos#193]
I was wanted to look for Water Stone shards and to help find them, I wanted to use my newly obtained Gyarados. While riding the Pokemon, I found a shard ore block, couldn't mine it while on the pokemon and got off the Gyrardos. I noted that I was not losing air while underwater, so I went up to the surface thinking it would fix it. I didn't pay any mind till I realized it wasn't going down again. I had never got back on the Gyarados. I learned that abusing bugs and glitches is a bannable offense. I asked a moderator, Lone6, and said that I should report it on here. This wasn't intentional and I don't know if this is a server bug or Pixelmon bug, but I hope it gets fixed. Thanks for reading this report,
  -UxerhintTV

**Comment by Rasgnarok** [comment]
Thank you for reporting it! This is indeed a Pixelmon glitch, can you repaste and forward to the tracker: https://www.pixelmonmod.com/tracker.php?p=2? That way the debuggers in Pixelmon can get it fixed.
