### ISSUE TITLE
Re-enabling placing shopkeepers

### ISSUE THREAD

**Issue by Archenemis** [ObliqueNET/Stratos#194]
Was told at one point NPC vouchers could place NPC shopkeepers. Was just curious to know how possible it would be to see that feature returned.

**Comment by Rasgnarok** [comment]
I don't know where you say that, but I just checked the store to make sure and it doesn't say that. 
![image](https://user-images.githubusercontent.com/18584380/57117888-56e03180-6d2d-11e9-8eb3-72d4c4582e0f.png)

**Comment by Archenemis** [comment]
Yeah. Is what it says. Just the other night I was setting up a shop and was going to place a shopkeeper NPC (I didn't know what they were and weren't allowed to place at the time) saw it wasn't on the list, so I said "Can you not place NPC shopkeepers?" And a couple of the staff were like "Yeah, you can." Then shortly after looking into it themselves were confused to not see it there.

It's not a huge deal either way and I'm sure me and others can make due with using the /warp shop on the server. But when they saw it wasn't on there they said I should put in a ticket on the github and ask if it could be added to the list of NPC's to place. So is how I came to asking the question the way that I had..

But if it never was a feature of the NPC vouchers, what would be the chances of getting it added to be one? Is fine if it's not so easily done or a pain to do, but can't know for certain unless I ask. Thank you for taking the time to read this whether it's added to the list or not!

**Comment by Rasgnarok** [comment]
I'll forward to @fatyg5 and @Vohras2 , I'd like their input on the matter

**Comment by fatyg5** [comment]
We have future plans that deal with placing shopkeepers in towns. I think we should wait until then to do this on Stratos.

**Comment by Vohras2** [comment]
I also don't like the idea, just for the simple reason that pixelmon's shopkeeper code sucks. It's very possible people could get a shopkeeper that I make an econ change too, and then they'd have that shopkeeper selling at the original price.

**Comment by Hiroku** [comment]
Closing from irrelevance. Shopkeeper stuff is indeed planned for the revamp, albeit not in the expected way
