### ISSUE TITLE
Diamond Crate Suggestions

### ISSUE THREAD

**Issue by Archenemis** [ObliqueNET/Stratos#195]
Copy and pasted from the suggestions tab:

I think a few of the items from the diamond chest should get a little bit of a buff in the way of numbers. There's items that are in the gold chest that you initially only get one of there. But getting them in the Diamond chest still nets you only one. I wouldn't think getting 2 Nether Stars for 1 diamond key be too bad.. Getting 1 from a gold key, either gives you 1 beacon, or lets you get back half your money.. letting diamond chests have them, you currently get back 1/4 your money or you get 1 beacon too.. Just doesn't sound right to give more money, but to earn less when compared to what you'd get from the gold crates. Maybe it's intended to be like that.. 

But I think the following items should be examined for the treatment: Cake, Creeper Heads, Nether Star, Ranch Upgrades, Everstones, Gender Vouchers, Egg move Vouchers.

Doesn't have to be by a lot, just adding in 1 extra (Or in the case of  cake and creeper heads, doubling it) should be very helpful (Though I personally think the Ranch upgrade should give you x4. So that you can upgrade your ranch in all 4 directions from winning it in that crate.)

Also ask that you analyze the items one at a time. You might not agree with all of the items getting a boost from the crates.

**Comment by Rasgnarok** [comment]
@Vohras2 More eco business, for when you have time.

**Comment by Vohras2** [comment]
Already buffed diamond crate like 2 days ago, including doubling ranch upgrades and nether stars.
