### ISSUE TITLE
Outdated Claim

### ISSUE THREAD

**Issue by trezela** [ObliqueNET/Stratos#196]
![2019-05-06_22 15 55](https://user-images.githubusercontent.com/46904272/57269716-198de380-704e-11e9-98f8-7d6a7aa8bfb8.png)

Looking to see if I can get this claim removed since it's outdated along with it's creator? [According to whoever responded on discord! Haha.]

**Comment by lolanonymous** [comment]
all town residents have been inactive past the thresehold, and thus the town and all its items have now been removed
