### ISSUE TITLE
Inactive Town Removals (Cherry Bomb/HawtPokemons/Omegatown)

### ISSUE THREAD

**Issue by nugsy** [ObliqueNET/Stratos#197]
![2019-05-09_21 31 15](https://user-images.githubusercontent.com/49658105/57502788-23a82000-72a2-11e9-8461-7e0d66f8f6ca.png)
Town: Cherry Bomb (owned/claimed by Thystu, been inactive 100+ days)

![2019-05-09_21 41 12](https://user-images.githubusercontent.com/49658105/57503008-37a05180-72a3-11e9-8f56-02535b7dd611.png)
Town: HawtPokemons (claimer is perma-banned, all members inactive for 100+ days)

![2019-05-09_21 42 43](https://user-images.githubusercontent.com/49658105/57503042-64546900-72a3-11e9-9724-58ea8b2f8ac8.png)
Town: Omegatown (owned/claimed by yoko795, been inactive 100+ days)

**Comment by lolanonymous** [comment]
all towns disbanded
