### ISSUE TITLE
Town Removal 

### ISSUE THREAD

**Issue by mairai** [ObliqueNET/Stratos#198]
![image](https://user-images.githubusercontent.com/50144595/57537503-090a9100-730c-11e9-953c-d33a20477e14.png)
![image](https://user-images.githubusercontent.com/50144595/57537545-1f185180-730c-11e9-90fe-4ff153e5fc83.png)
This user has been offline for two months, and their town literally consists of four wooden planks, would really appreciate if it could be disbanded. Thank you uwu

**Comment by Forensiic** [comment]
![image](https://user-images.githubusercontent.com/47290518/57566451-8e7c5880-7381-11e9-9e82-6e70d7e9729e.png)
This town too please.

**Comment by lolanonymous** [comment]
done
