### ISSUE TITLE
i got banned and i would like to return

### ISSUE THREAD

**Issue by bo68nito** [ObliqueNET/Stratos#200]
dear superiors
I understand that what I did was very disturbing and I understand that you lost trust in me, i am passionate about pokemon and Minecraft, as you can see in my town that i made quite an evolution since the past days, meaning thst im enthusiastic and happy to play, this game entertains me and i love it

**Comment by bo68nito** [comment]
is it possible if I can go backtoday so that i can help doing business with selling and buying???

**Comment by bo68nito** [comment]
i made so many friends in your server and I
 thank you for creating this for us

**Comment by bo68nito** [comment]
i understand what i did was unacceptable, trying to get free items

**Comment by bo68nito** [comment]
i will not disturb anymore and thank you for making me learn that this is not acceptable

**Comment by bo68nito** [comment]
my username is Bo68nito

**Comment by fatyg5** [comment]
It's a two day tempban. You will wait until those two days are done.
