### ISSUE TITLE
Jkaem Ban Appeal

### ISSUE THREAD

**Issue by JkaemtheGOAT** [ObliqueNET/Stratos#202]
I was banned yesterday (5/14/19) for "Using homes to TP to player towns and attempt to steal. Not the first occurrence." I would like to first clarify that it was not my intention to steal the legend if it did spawn at that sunflower plains. 

Regarding my "first occurrence", I would like to say that stealing the legend from Sam and not letting him know was not my intention. I knew Sam was camping for Azelf so he could give it to me as a gift for my generation 4 collection, but this does not excuse the fact that I abused my permissions to catch the Azelf. In hindsight, I fully understand that my actions were wrong and that I deserved to be demoted. (If given the chance, I would love to talk to an Admin/Manager about this situation to clear things up)

So, now onto the second occurrence. While I was flying around to find a flower forest, I stumbled upon a cool looking sunflower plains platform and decided to set a home since my old sunflower plains platform was rolled back due to the crashes. After I set a home, I came back to the platform later on that night (I think) and found a random player afk there so I realized that this platform is one that is being used and went on with my night. In the next day or so, I noticed that the player was still afk, and didn't know if they accidentally left their PC on while they went out of town or something. With this in mind, I remembered the players name and carried on with my day. Later on, something spawned in a sunflower plains (don't recall what it was) and I remembered that a dude has been afking a platform for a long time now and wondered if it has spawned on him. I proceed to go to my home I had at the platform to check to see if he was still afk there. My intentions when I went to the platform was to check to see if the legend had spawned on him, and if it had, I was going to message him ingame and then on discord to let him know that something spawned on him and that he should get on before it despawns (by game crashing, internet going out, server crash etc). When I arrived at the platform, I did not see any legendary pokemon and came to the conclusion that it had spawned else where and that the player afk didn't have to worry. 

Looking back on things, I completely understand the first situation and agree with the demotion. While I look back and thing more about the second occurrence, I do not believe that a permanent ban was necessary. I am not the type of person to try and steal things from people. Due to the first situation, I believe that some people may have a somewhat "bias" opinion of me, which I completely understand, and if there is anyway for me to make up for my actions while being staff, I would do so. If you have any questions or concerns about this whole mess, please just ask away. I would love to talk to anyone in VC about this to clear up any opinions or issues regarding me as a person. Thanks for reading and have a nice day!

**Comment by lolanonymous** [comment]
The first incident makes it quite hard to believe your intentions when you teleported to the guy's house for the legend that had spawned.

But given the fact that you actually did not steal anything I will show some mercy and drop this ban to a 3-day tempban. You are to remove the home from the guy's property and set it elsewhere. This will be your last chance, there will be no mercy on the next ban.
