### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by nativeofsteel** [ObliqueNET/Stratos#204]
So i was just banned for spoiling endgame to people. I didn't know that i would get banned for something like that. seems kind of silly to me that something that isn't in the rules could be a bannable offense. I was told that i would get unbanned if i made an appeal so here it is.

**Comment by nativeofsteel** [comment]
name is lencren

**Comment by nativeofsteel** [comment]
This is also my first time really playing the server and i worked kinda hard for the pokemon i have now so i would apreciate anything.

**Comment by Hiroku** [comment]
Spoiling Endgame is something people only do when they're trying to be a dick, since it serves no other purpose and people get very angry about it. You don't even apologize for it, instead implying it was silly of us to ban you in the first place. The ban stands. Terrible appeal.
