### ISSUE TITLE
Towns that require deletion

### ISSUE THREAD

**Issue by lolanonymous** [ObliqueNET/Stratos#207]
This is a thread for any towns that MUST be deleted because all the members have been inactive. Each case will be reviewed.

Follow this template when posting in this thread

Town name: 
Co-ords of the town base:

**Comment by Forensiic** [comment]
![image](https://user-images.githubusercontent.com/47290518/58150209-c2296f00-7c1a-11e9-8b80-23a298f066fa.png)

**Comment by Forensiic** [comment]
![image](https://user-images.githubusercontent.com/47290518/58530696-83ecfc00-8194-11e9-944d-293d6894c191.png)

**Comment by Forensiic** [comment]
![image](https://user-images.githubusercontent.com/47290518/58530760-c1ea2000-8194-11e9-8e0c-9d6e65e50dd4.png)

**Comment by Forensiic** [comment]
![image](https://user-images.githubusercontent.com/47290518/58531122-18a42980-8196-11e9-882c-c97f52281f9b.png)

**Comment by Sahvkriinov** [comment]
Ill get on it

**Comment by Sahvkriinov** [comment]
Towns have been cleared
