### ISSUE TITLE
Missing Vouchers: Jkaem

### ISSUE THREAD

**Issue by JkaemtheGOAT** [ObliqueNET/Stratos#210]
Shiny Up : 3
Size : 9 
Ball : 12
Nature : 1
Egg Move : 2
Gender : 2
Particle : 12
IV: 12
NPC: 3

This is probably hard to believe but I bought the top rank (comes with vouchers and 5 store keys) and I bought 30 crate keys, so that's where I got all of them

**Comment by Sahvkriinov** [comment]
Returned
