### ISSUE TITLE
somerandomguy910 Missing Vouchers

### ISSUE THREAD

**Issue by Somerandomguy910** [ObliqueNET/Stratos#212]
Last known screenshot of all the vouchers I had, These are the physical ones before they was converted: Event Voucher was used
Screenshot timestamp: 4/16/2019
![2019-04-16_21 28 39](https://user-images.githubusercontent.com/46073567/58127151-b02bda00-7be2-11e9-9f3e-747d2c7adf43.png)
Other Vouchers with Time Stamps:
5IV Voucher from Gold crate 4/23/2019 08:33:16 EST
Gender Voucher from Diamond Crate 4/23/2019 08:34:27 EST
Received 1 IV from elexjo 5/4/2019 08:52:19 EST

A few IV Vouchers was used on 4/20/2019 10:10:29 EST and 5/2/2019 14:46:49 EST (Possible of 2-5 used)

Gender Voucher used at: 4/28/2019 07:01:53 and 5/4/2019 08:54:41

Vouchers lost:
~42 IV Vouchers
2 Particle Vouchers
3 Ball Vouchers
3 Gender Vouchers

**Comment by MrBritish8** [comment]
Vouchers Returned
