### ISSUE TITLE
Lost Vouchers Round Two - big_cat_nug

### ISSUE THREAD

**Issue by nugsy** [ObliqueNET/Stratos#225]
This is the list of the vouchers I should have, after having them returned, I spent all the IVs, one pokeball, one size, and one particle on my Giratina, though I didn't spend any others. 
shiny: 4 
size: 8
ball: 7
nature: 0
egg move: 4
gender: 5
particle: 8
iv: 0 
npc: 4 (had 6 from contest win, used 2 at base)

https://imgur.com/a/SQ7m4Lb
Most recent screenshots I took of them all can be found here, though the list above is what they should be since I spent some to tune up my Giratina.

**Comment by lolanonymous** [comment]
should be refunded, if not @ me on discord 

-hrej
