### ISSUE TITLE
Lost vouchers ;w;

### ISSUE THREAD

**Issue by arantrix** [ObliqueNET/Stratos#226]
Hey it's me the spaghet guy aka _arantrix_ 😃 

i wanted to know if i could get following vouchers refunded:

1 size voucher
2 partical vouchers
9 iv vouchers

thanks in advance!
-arantrix
ign: _arantrix_

**Comment by arantrix** [comment]
![image](https://user-images.githubusercontent.com/50964923/58277424-03945880-7d9a-11e9-955d-3f8dca4e8764.png)github is stoopid and made it look weird
above is how you type it

**Comment by lolanonymous** [comment]
should be refunded, if not @ me on discord

-hrej
