### ISSUE TITLE
Lost Vouchers

### ISSUE THREAD

**Issue by thekingbeaver1** [ObliqueNET/Stratos#227]
Shiny voucher and particle voucher.

**Comment by Ferruccio88** [comment]
![unknown](https://user-images.githubusercontent.com/49542237/58321793-256afb00-7ded-11e9-983b-5fe30c2c1e84.png) 
![unknown](https://user-images.githubusercontent.com/49542237/58321810-2e5bcc80-7ded-11e9-835c-5d4b4f494b7b.png) 
![unknown](https://user-images.githubusercontent.com/49542237/58321817-33b91700-7ded-11e9-8e85-ea15265e6cef.png)
all the vouchers in here
besides the portal voucher

**Comment by thekingbeaver1** [comment]
They were both from beating the gym challenges, I had already used the size voucher.

**Comment by thekingbeaver1** [comment]
made a new one with better writing.
