### ISSUE TITLE
Pixelmon Adding Market

### ISSUE THREAD

**Issue by gyroball12** [ObliqueNET/Stratos#228]
Hey There I need help

I cant add pokemon to the market. The commands are right and i did connect my discord to my minecraft but its not letting me add any pokemon to the market at all. Can you help me?

**Comment by Forensiic** [comment]
What is your IGN? And what command are you running to add something to the market.

**Comment by gyroball12** [comment]
> What is your IGN? And what command are you running to add something to the market.
My in game name is Pokeking_2000 and my discord name is Valerian Drake

**Comment by Hiroku** [comment]
You haven't said what command you used

**Comment by gyroball12** [comment]
> You haven't said what command you used

what do you mean by command

**Comment by Hiroku** [comment]
Oh you edited it, nvm

**Comment by gyroball12** [comment]
when i  linked it says this Either that is not a name I recognize or you typed in a UUID and it wasn't correctly formatted.

**Comment by Hiroku** [comment]
Pretty sure I fixed this in the link map
