### ISSUE TITLE
Vouchers Missing again: Archenemis

### ISSUE THREAD

**Issue by Archenemis** [ObliqueNET/Stratos#233]
Missing 1 NPC Voucher and 2 Egg move Vouchers

They disappeared after last night.

Also. Side note. Egg Move vouchers were being weird for me. As you couldn't use them. You could try and click on a pokemon to use them on, and it wouldn't bring up the next menu. Just leaves you on picking a pokemon to teach an egg move to. Might want to test it yourselves.

**Comment by lolanonymous** [comment]
refunded
