### ISSUE TITLE
missing vouchers

### ISSUE THREAD

**Issue by Ferruccio88** [ObliqueNET/Stratos#240]
![unknown](https://user-images.githubusercontent.com/49542237/58380039-f2a23d80-7f79-11e9-954e-e459c85d83b8.png)
![unknown](https://user-images.githubusercontent.com/49542237/58380042-f930b500-7f79-11e9-9cef-98880d4bc288.png)
![unknown](https://user-images.githubusercontent.com/49542237/58380045-ff269600-7f79-11e9-9e1a-5a2d31febcfb.png)
1 gender voucher i know i lost some other vouchers but those are the only ones i can remember losing forsure because i was opening crates during when vouchers were disabled because i sometimes dont think and in which lost those vouchers (still have the statues and portal voucher tho sense portal voucher is physical and statues aren't voucher related) total count because forgot to put it their just now is 1 gender (forgot to screenshot that one when was opening diamond crates) 2 shiny ups 1 ball 1 size 2 particle vouchers (edited to add and remove comment made stating this as it makes more sense to just edit it in)

**Comment by Ferruccio88** [comment]
total count because forgot to put it their just now is 1 gender (forgot to screenshot that one when was opening diamond crates)  2 shiny ups 1 ball 1 size 2 particle vouchers

**Comment by Sahvkriinov** [comment]
Returned
