### ISSUE TITLE
Vouchers lost again

### ISSUE THREAD

**Issue by Somerandomguy910** [ObliqueNET/Stratos#241]
Most recent Screenshots of when I still had them:
![2019-05-21_16 39 09](https://user-images.githubusercontent.com/46073567/58416035-55650900-804e-11e9-86f6-db0e10885155.png)
![2019-05-21_16 39 12](https://user-images.githubusercontent.com/46073567/58416038-57c76300-804e-11e9-977b-e20aafc834f3.png)
![2019-05-21_16 39 14](https://user-images.githubusercontent.com/46073567/58416044-5d24ad80-804e-11e9-876f-b42657018b53.png)
![2019-05-21_16 39 16](https://user-images.githubusercontent.com/46073567/58416051-5f870780-804e-11e9-8254-2c7bd3d86ae5.png)

JaaFeel traded me 3 Gender Vouchers on: 5/21/2019 17:53:54 EST
Used 1 Gender Voucher on : 5/23/2019 07:15:57 EST

**Comment by Sahvkriinov** [comment]
returned
