### ISSUE TITLE
Boss pokemon on Stratos.

### ISSUE THREAD

**Issue by CenizaRey** [ObliqueNET/Stratos#242]
With the upcoming project, the fact boss pokemon fail to despawn after you end battle with them makes them very vulnerable to farming. This thread is to remind Hiro to develop a new spec type that makes boss pokemon despawn after you end battle with them.

**Comment by Hiroku** [comment]
Solved for next restart. Use `despawns` in the relevant quest PokemonSpecs (ie Pikachu lvl:50 despawns) and it will despawn on battle end, regardless of the config option.
