### ISSUE TITLE
Lost Vouchers

### ISSUE THREAD

**Issue by Lone6** [ObliqueNET/Stratos#246]
My townmate Jeso4 vouchers disappeared and just found out now.
He had to reinstall pixelmon with the 7.0.6 update so he doesnt have screenshot proof.
Hes also too lazy to make a github account -w-
He said he roughly had.
1x Shiny
6x Size
7x Ball
1x Egg
2x NPC
2x Gender
10x Particle

**Comment by Sahvkriinov** [comment]
Returned
