### ISSUE TITLE
how can i get unbanned?

### ISSUE THREAD

**Issue by JordiSins** [ObliqueNET/Stratos#249]

**Comment by MrBritish8** [comment]
Need some more context please, what was your ign and why were you banned.

**Comment by JordiSins** [comment]
> Need some more context please, what was your ign and why were you banned.

my minecraft name is SmaugSkywalker and i got banned for x ray and for something about signs(?)

**Comment by JordiSins** [comment]
> Need some more context please, what was your ign and why were you banned.

can you help me?

**Comment by fatyg5** [comment]
You haven't acknowledged the fact that you were xraying, or placing racially insensitive signs around and act like you have no clue why you were banned.

**Comment by JordiSins** [comment]
i know i were banned for using x-ray and i wont use it again. I was just asking if there was any way i could get unbanned.
