### ISSUE TITLE
Master Rank Kit : Enchanted Book glitched

### ISSUE THREAD

**Issue by Cheezegami** [ObliqueNET/Stratos#25]
**System**
Windows 10, Java 8 64bit update 192.
Pixelmon Reforged 6.3.4 using ATLauncher

**Environment**
On receiving master rank on my account "Cheezegami" and my friend on his account. We reached the master rank on the Oblique Stratos server.

**Encountered Behaviour**
We used the /kit master and it gave us a variety of items including a Enchanted Book with a description saying "protection.enchantment.level.0". Showing this book to an piece of armor and an anvil will make the equiped piece have protection 1.
We both received the same enchanted book with the same text.

**Expected Behaviour**
Upon receiving the enchanted book it would not have the zero level protection and a description that prints the data value of the item instead of the actual enchantment description. As well as a defined enchantment that corresponds to the reward.

**Visual Example**
![image](https://user-images.githubusercontent.com/23402028/50460221-6b25b380-0974-11e9-9c76-1d9d5921b99c.png)

**Comment by fatyg5** [comment]
Should be fixed. If not fixed, comment back on this ticket.

**Comment by deathybankai** [comment]
This just happened to me and another player, i think this ticket might need to be reopened.
