### ISSUE TITLE
can i be unbanned?

### ISSUE THREAD

**Issue by JordiSins** [ObliqueNET/Stratos#251]
I got banned for x-ray but im sorry and i wont cheat again. There is any way i can get unbanned?

**Comment by W4nkey** [comment]
LMAOOOOOO DUMB ASS

**Comment by JordiSins** [comment]
> LMAOOOOOO DUMB ASS

lol no u

**Comment by W4nkey** [comment]
You the one xraying and got caught.

**Comment by CJSPNagy** [comment]
Lets not use this as a message board please

**Comment by JordiSins** [comment]
you mad?

**Comment by JordiSins** [comment]
now i missclicked and closed , very nice

**Comment by W4nkey** [comment]
That’s why you closed it

**Comment by JordiSins** [comment]
if you can read i said " i missclicked"

**Comment by W4nkey** [comment]
Lmao you a dumb ass you not getting unbanned.

**Comment by JordiSins** [comment]
no one asked you nothing
