### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by DarkKermit** [ObliqueNET/Stratos#253]
On Oblique, About a year ago I was banned from Stratos for Dm Advertising

I had donated a lot of money to that server (Around $100) And I was wondering if I could be unbanned.
My Username is Trapachu(Name when banned)/Dark_Kermit(Current Name)

Please contact me soon

**Comment by Rasgnarok** [comment]
Considering you were banned for advertising another server to players via DMs, your purchases (not donations, as these are transactions) do not clean you off of the reason for your ban. For the record, no amount of money would make me apply rules differently. In this ban appeal, you also do not seem apologetic or regretful of your actions, that were done in a lash out against staff that had already warned you plenty for attitude mishaps.

For those reasons, this ban appeal will be declined.
