### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by ScheeK33** [ObliqueNET/Stratos#263]
Ban Appeal regarding IXpig.
I'd like to know why I was banned, it seemed like after I exposed that MrB got demoted for faking proof that I was banned. But the reasons you guys said in chat was because "he has alot of notes".

**Comment by CenizaRey** [comment]
The job of a moderator isn't easy. Cases like yours require a lot of deliberation and we'll sit there discussing it until we all reach a unanimous decision. The fact you "had a lot of notes" for low-to-mid range offenses made deciding your fate particularly difficult, but here's the conclusion we reached:

After the incident with MrB, you were already a known troublemaker with a tempban under your belt, as well as several notes for a variety of reasons. You behaved in a rude, frankly unacceptable manner towards our team on a regular basis, for which you were banned for a day. But here's the nail in the coffin: On top of continuing to stir the pot when your tempban was up, you decided to start selling falsely nicknamed pokemon on the market, such as a cloned mew as a mew that hadn't been cloned at all, as well as churning out Eevee's to the majority of the general public, thereby breaking the rules of our delicate economy.

We don't ask for much out of players, but to play by our easy-to-follow rules and be kind to one another. But the fact that as soon as MrB was retired, you leapt on to the server to place emphasis on how and why he was retired in the first place, for no possible reason but to mock the remaining staff team, and to rock the boat. And when asked by whom you received the situation so quickly before we unveiled it to the public, you had the audacity to reply with "a little bird". Ban appeals are for people who have remorse for their rule-breaking, who convince us that they can do better in the future. Not people who storm in to our Github, make a thread accusing _us_ of doing wrong, and roll with the punches.

Hiro was logging onto Stratos to inform the population of MrB's situation, as under the new leadership we prize transparency above all things. So if you had kept your head down, and not tried to claim some falsified sense of glory over the loss of one of key staff members, perhaps you wouldn't have placed the straw that broke the camel's back.

If you can show us one iota of physical evidence or proof that you can respect the rules of Stratos and every single player on it, perhaps you'll have a shot of making a real ban appeal. Until then, IXpig.

**Comment by ScheeK33** [comment]
Hey, I mean, you are completely right. It was wrong for me to go at staff, but, in some cases it was totally right. But regardless of that, I know I've been causing trouble mainly with staff members, which is wrong. I know they are just trying to do their jobs as best as they can and which I made it harder for them to do. My apologies. I'm not usually the best at making these type of things, and it's really hard for me to say sorry in certain cases, but sorry regarding this.

**Comment by CenizaRey** [comment]
Thank you for having the courtesy to apologise, but there comes a tipping point. You were a known troublemaker, and you revealed the Mr.B situation to the public as if it was some kind of deep, dark secret, when it wasn't. That was another attempt at troublemaking, and the fact is troublemakers don't last long on Oblique. For these reasons, you will not be unbanned.

**Comment by ScheeK33** [comment]
Understandable, but it seemed like it was a secret, as most of the staff team tried to hide the fact that he was, and they straight up lied about it to cover. But regardless, I know I shouldn't have kept going. My apologies as stated, maybe I'll try next reset.
