### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Thepigmaster99** [ObliqueNET/Stratos#265]
Hi, I´m Thepigmaster99, last week i stole a player stuff and then I sold it so i could buy my favourite legendary, Entei. I know that was a bad decision and that stealing is one of the worst thing ever. That´s why I need to say that I have been like a little kid, stealing just for my benefit. This server is my favorite and I play almost everyday for at least 5 hours, and now that i have been banned, i´m really sad, and i would like rejoining the server, i promise i would never stole anything, this server is the best place and i would give and pay for what i done, I know stealing is bad, but please pardon me. This server is everything for me. Thanks for all.

**Comment by W4nkey** [comment]
Yeah lmao you not getting unbanned

**Comment by CenizaRey** [comment]
The contrary, actually. You do seem genuinely sorry for what you've done here, and we've decided that you should be given one last chance. This doesn't come free, however, as you will remain banned for the next 3 days. In addition to that, your permanent ban will be reinstated if you break the rules again.

Also, W4nkey, please try not to comment on these anymore.

**Comment by Thepigmaster99** [comment]
Thanks for all, :)
