### ISSUE TITLE
Got discord banned

### ISSUE THREAD

**Issue by MKFusion** [ObliqueNET/Stratos#267]
My discord name is Biatrixx#5752 and i got banned(i think) by sending Unepropriate pictures (im not realy sure) and at the time i didnt think discoud server would affect that much, for talking with staff members and make some trades with other people. im realy sorry and i wont do it aggain

**Comment by fatyg5** [comment]
You thought posting pornography in our Discord was a good idea? For the overall mentality you have to have to post something like that, as well as the fact that you didn't think posting inappropriate things would be wrong after being warned about it, you will stay banned.
