### ISSUE TITLE
Coud you guys pleasae restar the server

### ISSUE THREAD

**Issue by MKFusion** [ObliqueNET/Stratos#268]
I'm having an issue that i had yesterday at the same hour and i cant play on ther Stratos server because of the lag.
No , its not my internet connection fault
No, ther is no one using my internet at home
Yesterday they did restar the server and my connection got perferct
and this issue just happens at this time of the day, besides that my connection is always good 

im just submitting this because i would like to enjoy a little more playing on this server :\

**Comment by Hiroku** [comment]
Has been restarted, but I don't expect that unless others were having the same issue that this is caused by server restarts. Seems unusual to me.
