### ISSUE TITLE
Shulker box box went poof.

### ISSUE THREAD

**Issue by Gomer604** [ObliqueNET/Stratos#269]
Hello wonderful people, 
It is I, Gomer604.

Today I was pushing my shulker boxes with my piston to see if I could make an automated sorting system for all my juicy loot.
When upon lining up shulker boxes like shots on a Saturday night, I flick the button and the piston goes off!
When it retracts the shulker box broke into item form (Keep in mind I was watching chat for item clear entire time) and disappears like Spider-Man at the end of Avengers. Snap! 

After realizing what had just happened I was much like Iron Man and very much upset.
Inside the box was a lot of different balls, specifically but not entirety. 3 Master balls, 2 park balls, 32 rare candies, 6 exp shares, and the rest were either a blur and I can part ways with or just different pokeballs.

Now unfortunately I do not have ocd to screenshot my chest(s) so I have no proof except a few people I flex the loot on and my word of mouth. Nug, was first responder to my  sad whimpers of eternal lost and sadness and helped me via directing me to here to fill out one of these saucy boys.

If someone could help me recover my precious cargo that would be much appreciated. I would probably name a stick after you and put it on an item frame somewhere probably nobody would see it.

Thanks for reading and have a nice day.
Kind regards.
Sincerely,
Forever yours,
~Gomer604.

**Comment by CenizaRey** [comment]
This is a fantastic thread, and your items seem plausible. In the future, try not to play around with pistons and entities, they're finicky on Sponge at the best of times. I'll repay you the next time you're online.

P.S. Make the stick out to "Best boi Cen"

**Comment by Gomer604** [comment]
You've left me in a sticky (pun) situation now, thanks for the help!
