### ISSUE TITLE
Please unban me 

### ISSUE THREAD

**Issue by Squldwerd** [ObliqueNET/Stratos#27]
Dear: Staff
I am sorry for everything i did and want to get unbanned. I will never do anything again and you can mute me in chat forever so i cant do anything. Also you can take away all my pokemon and make me start from scratch. I am deeply sorry and wont bother you anymore. Have a good rest of your day.
Sincerely: Squldwerd

**Comment by Rasgnarok** [comment]
Oh, you opened a new one. Either way, I have reviewed the server logs on my end and I deem your ban appeal sufficient. I have unbanned you. I'll review your friend's ban in the other ticket: https://github.com/ObliqueNET/Stratos/issues/26

**Comment by Squldwerd** [comment]
I think i am still banend on terr a which is the server i was last in and that might be why it says i am banned still
