### ISSUE TITLE
Ban Appeal - IXpig

### ISSUE THREAD

**Issue by ScheeK33** [ObliqueNET/Stratos#271]
Hey Oblique Staff,

First off, I want to apologies again for the way I acted. I know it's only been almost two weeks, but would love to make another appeal. I've changed from previously, I know I was pretty toxic, and the evidence is right there to prove it, but I've changed. I know actions speaks louder than words, so I'd love if you guys would be able to give me another shot. I know it was wrong to keep arguing with staff and going against what they said. I fully understand that now, and I really do hope you guys are able to give me another shot. I've been only playing for a week and I'm already perm banned :(.

Hope to hear & discuss with you guys soon!

Best Regards,
IXpig

**Comment by fatyg5** [comment]
You already had a second chance given and you ruined it. You definitely didn't magically become a better person in two weeks nor were you banned two weeks ago anyway.

You will not be unbanned.

**Comment by ScheeK33** [comment]
Sorry, just want to touch on this. When was I given a second chance? As far as I know, and with the staffs I spoke with, I was on thin ice and which I was banned the first time.

**Comment by CenizaRey** [comment]
Normally I wouldn't respond to that, considering nobody here owes you a response; but I don't like to leave things unfinished. You were temporarily banned prior to your perm ban for 1 day. When you came back from that ban, _that_ was your second chance, and you squandered it.

You have not changed as a person, this is evident in the fact you literally just attempted to argue with Faty's ruling. Had you changed, you would have accepted the reality of your situation. Once again, it proves your argumentative nature got the better of you, and it isn't going anywhere anytime soon by the looks of things.

You can be whoever you want to be if you put your mind to it, but no matter what you choose to be, it won't be on Oblique.

**Comment by ScheeK33** [comment]
Oh, I see. Thank you for the response, I honest to god did not know I was temp-banned previously, I'm assuming it was because I gave someone like 40 Eevees. My previous statement was me just wondering, as I honestly did not know I was temped.
