### ISSUE TITLE
Wrongly banned, trigger happy staff.

### ISSUE THREAD

**Issue by Gomer604** [ObliqueNET/Stratos#274]
Hello,
Gomer again here just wishing everyone a happy Saturday.
I know I'm having one when I privately discuss plans with a member about how to make money and get banned without warning!

So, I will explain everything in perfect detail and with pictures upon request!
I have nothing to hide so a trigger happy staff member to expose, so let's get into it shall we?

It all started as a fantastic day, I log into my favourite Pixelmon server and started messaging my boy Troy about a plan I had adapted from a money course I took (Being poor gets you nowhere) so I thought it would be a good idea to implement it (strategy that is 100% complaint with the rules of the server) I say in /msg (which is a **private** form or messaging) asking if he has 100k to help kick start our new empire of buying and selling items, only to be banned! Now I skipped a bit there but I will get to it in one second, quick lesson in phrasing of words. 

I say to Troy "I took economy courses" and "I'm going to break the economy of this server"
You see, phrasing is key. The staff member got too trigger happy and immediately banned me. Preventative but also very foolish because now I write this long post to waste my weekend from work because of your clouded judgment. 

When Kim K "broke the internet" did she really or was it just a word play to make it seem more interesting? 
Now I can see how that would be concerning to someone with power, but to continue about it. I say to Troy "Let's go in discord, I know the staff can see these messages and I don't want them stealing my money making method, they gotta work for their money."

So because I don't want staff to steal my idea of making money thus making my profit less (if everyone does it - less demand with more supply) a child could understand that concept.

So the staff failed to review the situation and banned me on the spot because I didn't want to expose how to make money to all the staff.

Now to me that sounds like a power struggle right there and should be looked into but that's not my concern.

Like I said, I had all the pictures of every word I said to Troy in my /msg (Funny how it's meant to be private but I am about to show it to everyone) 

Ask Troy if you want, also fun fact. He never went onto Discord so I can tell him so what's written in the ban is also false information (Sloppy work) 

Please be careful next time because that's how you lose committed players. I work hard for my poke-dollars just as the next guy, to have a staff member be able to take that all away because they felt threatened by my words of how to make a couple extra hundred K is in my eyes a compliment not only cause the staff banned me for some odd reason, but they truly believed in that I would break the economy of the server. That means a lot, but after looking into the /rules I can't find it anywhere stating I can't make money? If my method is EULA/server rule compliant. What was the rule/crime I broke? Nothing? Hmmm, not the best judgment.

Pettiness aside, am I salty? Yes and no.
Mistakes do happen, I can look past this but I do find this a form of harassment as I am being singled out on making some money.

**Comment by CenizaRey** [comment]
Ban appeals are a lot more likely to be accepted and you're a lot more likely to be pardoned if you explain your situation clearly and concisely. The meat of this thread is mostly inapplicable metaphors and therefore it's hard for anyone to understand what you're driving at. On the surface level, you seem angry and bitter and that isn't the impression you want to give off. Ban appeals are for apologies. _You_ don't necessarily need to apologise for anything except a communication error between yourself and staff, a favour which the banning moderator will return.

Side note, we make it very clear in the /rules that moderators+ are capable of seeing your private messages. The fact you've stressed the point that they're meant to be **"private"** proves to us that you actually haven't properly read the rules. Here's how this is gonna work. Start again, make a new, more concise appeal. Perhaps when you've cooled off a bit. At which point we'll review, confer amongst ourselves, and sort this whole mess out.

**Comment by Gomer604** [comment]
Roger dodger sauce boss.
