### ISSUE TITLE
new mounts cuz we both know you love me faty and you don't want to say it

### ISSUE THREAD

**Issue by doughnutchicken** [ObliqueNET/Stratos#278]
first Vivillon because in the anime the gym leader viola had one and was able to hold on to it and fly well it shot out some pretty cool lazers and stuffs and i am not that heavy.

second Sharpedo because we all know you have had a thousand requests to make this happen and Sharpedo could easily carry a player.

thirdly Pinsir because look at him he is the most epic looking bug ever he even has a cool mega and could easy carry this should be a fly mount.

finally Rattatataatata because dovah said so and would hurt me if i didn't

love your favorite doughnut flavored chicken 
p.s you love me faty

**Comment by lexjo** [comment]
Also Drampa because it makes sense

**Comment by fatyg5** [comment]
There's a mount ticket, please move them there
