### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by bluedragon89206** [ObliqueNET/Stratos#279]
Ign Bluedragon89206
I was recently banned from the stratos server for having a xray mod on my client, I have forgotten that I had it installed on my client, I installed it a while back because my friend started a server where hacking was allowed, if needed I can provide screenshots of when he invited me to said server(I played on it for a few days then lost interest). I have not used the mod on the pixelmon server and if possible I would like to get unbanned.

**Comment by Grassip** [comment]
Because this is your first offense and you were banned only for having it on your client and not using it in-game, you are pardoned. Make sure it is no longer installed before you join the game once again. There won't be any more second chances if you are caught with it a second time.

**Comment by bluedragon89206** [comment]
okie dookie
