### ISSUE TITLE
smeargle bug 

### ISSUE THREAD

**Issue by manta-Frost** [ObliqueNET/Stratos#28]
everytime i use sketch i learn the move for the current but after the battle is over the moves disappear

**Comment by JettisonedGames** [comment]
Would it be possible to get some more details on this issue?  Are all moves disappearing off of the Smeargle, or is the move being reverted back to sketch?

**Comment by fatyg5** [comment]
After testing this, it seems to work fine. I had tried to speak to Manta in the chatbox, but got no reply. If this is still an issue, recomment on this ticket or open a new one.
