### ISSUE TITLE
Alright and were back with a new appeal...

### ISSUE THREAD

**Issue by TheGameTM** [ObliqueNET/Stratos#281]
In this appeal i will go into more detail.
I was playing with some buddies on your pixelmon server. It was really late at night around 3 oclock EST. We were just having fun messing with people being in our tired state. This morning i wasnt planning on doing anything bad so i messaged my friend who i am in discord with a racial slur and that caused me to get banned. It made him laugh but when he realized i was banned even he thought i shouldn't get banned as at such a late hour kids or teens wouldnt be on and it was just a PM. I should be unbanned or a lower sentence than a perm like a week ban. I showed lack of respect and i am truly genuine in this appeal im very sorry.

**Comment by TheGameTM** [comment]
I am sorry as i stated before i love the server it is hard to find a pixelmon server like yours. It is a perfect balance of what a pixelmon server should be.

**Comment by Grassip** [comment]
The rules are the rules, no matter what time or who is online. You are blaming your rulebreaking on being "in a tired state" and if we can't trust you to be respectful and polite when you are tired that just gives us yet another reason why we are not unbanning you. Some of the things you said were absolutely horrible, and we take racism extremely seriously.  Also, you weren't banned for the PM you sent, you were banned for the countless racist jokes you made and for being disrespectful and racist in general chat.

**Comment by TheGameTM** [comment]
Okay i understand but you should consider it as it is my first offense

**Comment by Grassip** [comment]
You have been given your answer. You were warned multiple times and muted before you decided to continue and you were banned. It certainly was not your first offense. 
![image](https://user-images.githubusercontent.com/47408346/60389436-7de58600-9a86-11e9-9918-dc0eef92eaba.png)
![image](https://user-images.githubusercontent.com/47408346/60389440-8fc72900-9a86-11e9-997d-92aeca248f79.png)

As you can see here, there were multiple times when a staff member warned you to stop. This is the end of this discussion.

**Comment by TheGameTM** [comment]
Okay ill leave in peace just know i gave peter back his xp share

**Comment by TheGameTM** [comment]
also why were my town members not banned

**Comment by TheGameTM** [comment]
like now their having fun without me like i hope you know this is not okay idc if i was racist its kinda stupid i was looking through other appeals and saw the stuff you let fly

**Comment by CenizaRey** [comment]
You do not tell us what we should be doing. You are appealing to US, not the other way around. The decision is final. You will not be unbanned.
