### ISSUE TITLE
Boutta leave with a bang.

### ISSUE THREAD

**Issue by TheGameTM** [ObliqueNET/Stratos#282]
I played the server for a week and got banned. I guess I cant talk to friends without being banned by staff who can see private messages. Yall saying it wasnt because of that. But i got banned right after. So thats a massive L on your part. Abusive staff lmao

**Comment by TheGameTM** [comment]
and clearly if i was banned for the messages it wouldve been last night

**Comment by CenizaRey** [comment]
We make it clear in /rules that staff can see private messages. A ruling has been made and you will never sign onto the Oblique Network again.

**Comment by TheGameTM** [comment]
okay lmaoooo thats not the point it was stated that i wasnt banned because of the private messages

**Comment by TheGameTM** [comment]
Grassip literally said, "Also, you weren't banned for the PM you sent"

**Comment by CenizaRey** [comment]
You are not owed an explanation. This is totally futile, you will not be unbanned. Get off our board.

**Comment by TheGameTM** [comment]
i am owed a explanation

**Comment by Grassip** [comment]
That wasn't the only reason, but it was the last straw. It was more of the fact that you weren't banned _only_ for the PM. Either way, this is going to get you nowhere.

**Comment by TheGameTM** [comment]
ik it wont but it just stupid the way it was stated
