### ISSUE TITLE
Im sorry.

### ISSUE THREAD

**Issue by TheGameTM** [ObliqueNET/Stratos#284]
Just wanted to say im sorry for all the arguing and bickering im on a alt account now and i wont get banned

**Comment by TheGameTM** [comment]
yall really ip banning people?

**Comment by TheGameTM** [comment]
what have i done on this alt account that makes me get ip banned

**Comment by Grassip** [comment]
It's not about the account that breaks the rules, it's about the person playing. Just because you have another account doesn't mean you have a fresh start.

**Comment by TheGameTM** [comment]
Okay? what about my town mates

**Comment by TheGameTM** [comment]
they literally did the same shit i did

**Comment by CenizaRey** [comment]
You’re not as sorry as you say you are, are you? Please stop trying.
