### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by AZJumbo** [ObliqueNET/Stratos#286]
Hello Staff Members,

I am inquiring about the permanent ban I received on 6/29/19. I was saying unintelligible and stupid stuff in chat, but nothing detrimental or antagonizing towards anyone. Dead_Of_Pool and I are in a discord call and I was very surprised to see I was banned after being out of chat for roughly 10 minutes. I enjoy playing on this server a lot and I've invited two of my close friends to play with me and it would really suck to stay permanently banned. I will admit in the past I have acted a fool in chat and received a temp ban, but I came back to the server after and behaved myself and will continue to do so if this ban is lifted.

Thank you,
Gabriel (AZJumbo)

**Comment by Grassip** [comment]
Alright, you have been quite inappropriate in chat before and you have received multiple warnings. However, I am going to shorten your ban to a 3 day temp ban, and give you one last chance. If a staff member ever tells you to stop doing something, take that to heart and _remember not to do it again._

Respect the staff and don't try and stir things up in chat anymore. This is your final warning.

**Comment by kaderator** [comment]
Hey💕💕❤💖❤💗💗💘💖💟💗💞💝💞💗💞💝💗💖💝💞💗💖❤💕💖💗💕💖💗💞💝💞💟💗💖❤💕💓💖💗💞💝❤💖💗💞💝💖❤💗💟💖💗💝💞💗💕💖💗💞❤💝💕💗💗💞💝💞💗💖💕❤💖💗💞💟💘❤💕💘💗❤💖💗💞💝💞💗bro💕💖❤💖💗💗💖❤💗💝💞💗💖💗💞💝💞💗💖💕❤💖💗💞💝💞💗💖💞💗❤💖💗💞just💖💗💞💝❤💖💗💞💝💞💗💖💕💟💝💞💗💟💖💕💝❤💖💗💞💝💟❤💘💕💗💗💞💝💖💟💘❤💕💖💗💞💝💘💗💞💝💖💗❤💞💘💝💖💗💞💝💟💞💘💖❤💗💞wanted💟💝💞💘💖💗💕💖💗💘💞💝💓💕💘💗💞💓❤💘💕💟💗💘💞💗💝💟💓❤💘💝💞💗💕💗💞to💘💟💘❤💕💖💝💞💗💖💕💝💞💗💞💖❤💗💗make💘💕💖💗💞💝💟💖💘💗💞💝💞💗💖💘💕💗💟💞💘💝❤💓❤💘❤💗💞💟💘❤💕💗💘❤💞💗💘💖💘💕💗💘💞❤💝💞💘❤💟💘❤💓❤💘❤💓💓💖💗💘💞💟💘❤💓💘💕💘💗💞💟💘❤💓❤💖💘💗💘sure💘❤💓❤💘💖💞💟💘❤💓💖💘💗💘💞💟💘❤💓💖💘💗💘💞💟💘❤💓💕💗💘💗💘💞❤💗💖💘💗💘💞💟💘❤💕💘💖💗💘💘💓❤💘💗💞💘💝💕❤💗💟💝💘💞💗❤💕💖💘💝💟💞💘💗💟💗💝💞💟💗💘💕💖💝💘💞💗💕💟💝💗💘💖❤💕💝💗💘❤💓❤💟💖💘💕💗💝💗💕💞💗💘💟💘❤💓💕💘💗💞💟that💘❤💘❤💓💘you💘💓💘💖❤💕💘💗💗💖💞💗💘💖💕💘💗💘❤💓💘💕💘💖💗❤💞💘💗💖❤💘❤💓💘💖💘💗💘💗❤💘❤💓❤💘💟💘💖💗💘💞💗❤💕💘💗💘💗💞💝💘💞💘💗❤💕💝💟💞💘💖❤💖💞💟💘💞💝know💘💟❤💓💘💘💘💓💘💕💘💗💞💟💗💘💖💝💟💞💘💗💕💝💘💗💓❤💘💖💞that💘❤💟💘❤💕💘💗💞💘💗💖❤💕💘💗💗💞💗💘💖❤💕💘💖💘💗💞💘💗💖💟💘❤💓❤💕💘💝💘💖💕❤💖❤💝💘❤💓❤💕💘💖💝💘💞❤💗💕❤💝💘💗💘💞💝💟💘💘💞💖❤💕💘💝💘💞💘💗💟💝💘💞❤💗❤💕💝💟💘💗💟💘💝💘💞❤💖💘💕💟💞💘💗💟💝💘💞💖💘💕❤💘💝💟💗💘💖💞💟💗💘💞💘💝💘💗💕💘💝💟💘💗💟💘💞💖💕💘💝💞💘💗💟💝💘💞💕💘💖💟💝💘💞💝💟I💘❤💕💘💖💟💘💞💗❤💓❤💕💘💝💟💘💞💘❤💟💘❤💘💖💞💘💗💟💞💘💗💕💝❤💞💘💗💓❤💕💘💖💟💘💞💖💟💝💘💞💞💘❤💕💘💝💟💞💘💖💘❤💘❤❤💕💘💖💝💞💘💝💟💞💘💞💟💝💘💞❤💖💕💘💖💟💘💗❤💕💘💖💟💞💘💗❤💓❤💘💟💘❤💓💘💕💟💖💝💘💞❤💗❤💕💘💝💟💞💘💖💘💟💘💞💘💝💘💖💘💗💘❤💕💘💖❤💗💗💘💕❤💖💘💗💘💗❤💕💗💘💘❤💗❤💕💗💘❤💖💘💕💘💗💗❤💖❤💖💘💗💘💗❤💝💖💟💘❤💘💖💟💗💘💗❤💖💓💖❤💗💘💞💗💟💘💗💟💞💘💗fuckedyourwife💟💘💗❤
