### ISSUE TITLE
Berrie grow bug

### ISSUE THREAD

**Issue by ThaGreenDuck** [ObliqueNET/Stratos#288]
Currently I'm trying to farm on berries, while doing so I have found out there is a bug in the growth of the following berries:

- Hondew
- Grepa
- Tomato

In the time spawn of them still being in the second growing stage, I have already harvested:

- Pomeg
- Kelpsy
- Qualot

Twice.

https://cdn.discordapp.com/attachments/479746426751156225/595963289914048542/unknown.png

I already posted this in the #staff in Discord, so was told me to create this issue.

**Comment by ThaGreenDuck** [comment]
I think there might be a bug on the following berries as well:

- Figy
- Lum
- Yago
- Wiki
- Iapapa

**Comment by fatyg5** [comment]
Seems to be a thing with Pixelmon sucking with berry growth. Hopefully they will rewrite the berry code, but for now, not much we can do. Closing
