### ISSUE TITLE
Wrongful Ban

### ISSUE THREAD

**Issue by Phattty** [ObliqueNET/Stratos#289]
I was recently playing on the Stratos server when I addressed a pokemail to my friend, in which it contained the word "n*gga." This was personal mail, but as a joke he gave it to a staff member name ChrissuKun, for which I was warned, and my friend told him it was a joke. It was fine for all of two minutes, when my friend called him "Master Chris" in chat, being new to the server and seeing his dex rank in front of his name (which was master). He was then muted for 5 minutes, so I /marry gifted my friend a pokemail asking why he was muted so he could give it to him, as he didn't have one of his own at the time. He gave him the pokemail, and I then /marry teleported to my friend. I wasn't aware of the mod's actual ign since I wasn't there, so I named him "Master Chris" in the mail, as that's what my friend said his name was. I was then muted for 5 minutes as well, even though I said nothing in chat. My friend asked why I was muted, and I was then given a day ban for "racism" for calling him Master Chris. My friend argued with him for a minute, and was then given a 30 minute mute. I see this as very unfair and abusive, and he was very unexplanatory in his explanation for my ban, saying how "Master Chris" was being used in a racist context. This is very annoying, and I would like an apology from Master Chris. 
          Bes Regards- Phattty

**Comment by Grassip** [comment]
You not only continued to call him that after he told you that it was racist and asked you to stop, but you also argued with him and you were specifically attempting to offend him. No matter what you personally think is offensive, if another player or staff member requests for you to stop saying it to them, you stop. It clearly states in the rules that you are to "be respectful to everybody, no matter what." You continued to say that to Chris, and that was considered as breaking our first rule. You then continued to go to Terra and break the rules there, which certainly did not help your case. Not to mention that this appeal has no apology or recognition that you were in the wrong whatsoever. You were not wrongfully banned, you were breaking the rules and making another player uncomfortable after several warnings. Therefore, you permanently banned.

**Comment by Phattty** [comment]
I do realize that what i did was wrong, but don’t think a permanent ban was justified. Although I did call him Master Chris once, you can see in chat logs I never called him that once after he asked me to stop. I also stated later that I would accept the one day ban, after realizing the policy on this behavior. You claim there was several warning but he only said once not to call him that, and it was after I said it the first time when I then stopped. In regards to the racism, I do regret what I did, and apologize. I know what i did was wrong, but do not think I deserve a permanent ban.
