### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by IceIceBaaby** [ObliqueNET/Stratos#291]
I got banned in hub by auto ban system i was with a friend in lobby he was asking what my other friend got banned for so i said he got banned for saying the "n word" in chat and i got auto banned. It was just me in the chat i didn't think i would get banned i know its my fault i did say the n word in chat but not in a vulgar way it was explaining to my friend i will no longer say the n word if i truly do get unbanned i am very sorry for doing this i started playing 3 weeks ago and am having a lot of fun on stratos i would hate if i could never play again please help me play again.
Thank You for your time
-IceIceBaaby

**Comment by Grassip** [comment]
You were already warned about racism and knew that saying that word was against the rules. You were well aware that saying that word was not allowed and did it anyway, therefore you will not be unbanned.
