### ISSUE TITLE
im baned im french an i ave make a trad eror

### ISSUE THREAD

**Issue by antoine59970** [ObliqueNET/Stratos#293]
i ave ben baned for x ray whith any explanation and evidence
![image](https://user-images.githubusercontent.com/52713470/60953312-3ae4a780-a2fd-11e9-95cf-fae6eca7d099.png)
![image](https://user-images.githubusercontent.com/52713470/60953333-433ce280-a2fd-11e9-8719-836fe985dc6f.png)
![image](https://user-images.githubusercontent.com/52713470/60953345-4a63f080-a2fd-11e9-8264-c945fd65a716.png)

my mod texture pack and the resons of ban
im fernch an i ave a bad english level
i ave a bad conexion il lag and the chunk dont charge the admin evidence is that 
![image](https://user-images.githubusercontent.com/52713470/60953486-8a2ad800-a2fd-11e9-9d7e-469da544b29a.png)
![image](https://user-images.githubusercontent.com/52713470/60953497-8eef8c00-a2fd-11e9-85b2-695bc268560f.png)
i forgot the dont in this message beacose i ave oben a box
and i see the lava flow and the mosy stone at the first pic 
thank an be patient of my bad englich (i ave 3/20 in english thank google)

**Comment by Grassip** [comment]
You were watched closely and your habits clearly showed that you were using some form of x-ray whilst mining. Not to mention, in your last appeal you admitted to taking something from an unclaimed base, which is against the rules and is considered a second bannable offense.

Either way your answer was provided to you in your first appeal: you aren't going to be unbanned.

**Comment by antoine59970** [comment]
i never use x ray i dont know how ti instal this

**Comment by Rasgnarok** [comment]
C'est dommage, car si tu aurais eu un peu plus de tête, tu aurais pu avoir ta deuxième chance. Malheuresement pour toi, tu as aussi décidé de faire ceci: 
![image](https://user-images.githubusercontent.com/18584380/61004700-91b9a380-a334-11e9-83f3-f55e21ad7de7.png)

Donc non, c'est pas ton manque d'anglais qui cause problème, mais ton goût pour les mensonges.

**Comment by antoine59970** [comment]
J'eatait énervé j'ai agis pour faire chiez

Le mer. 10 juil. 2019 à 23:03, Rasgnarok <notifications@github.com> a
écrit :
