### ISSUE TITLE
Ban Appeal.

### ISSUE THREAD

**Issue by Poofca** [ObliqueNET/Stratos#294]
I have been banned due to my use of x-ray on Stratos. I have been playing on the server for about a week now, and I do admit that I was x-raying for a small amount of the time I was on the server. I would desperately appreciate a second chance, as I have since then removed the x-ray resource pack from my game. Please consider unbanning me, I'm very sorry for what I have done and I will never x-ray on this server or any others again. Thank you for your time.
![image](https://user-images.githubusercontent.com/52751327/60979650-6ce62000-a376-11e9-8cb1-301de324be82.png)
![image](https://user-images.githubusercontent.com/52751327/60979690-7bccd280-a376-11e9-86c5-30cf1663f4e1.png)

**Comment by Grassip** [comment]
Thank you for being honest, and for removing the x-ray. We accept your apology and we will unban you, but know that if you are caught a second time you will not be given another chance.
