### ISSUE TITLE
Ban Appeal Madnessrider

### ISSUE THREAD

**Issue by Madnessrider** [ObliqueNET/Stratos#295]
I don't have that much too say, but I thought xray would be fun. But now I'm banned and it's not that fun haha. Sorry in the first place. Second I would like to get another chance, because it was a mistake, but I don't have a bad history.

Excuse me

Madnessrider

**Comment by Grassip** [comment]
You have been tempbanned for 3 days and have had multiple warnings on breaking the rules, yet you claim to "not have a bad history." You have been on this server long enough to know x-ray is not permitted. You will not be unbanned.
