### ISSUE TITLE
Sellable Emerald Blocks

### ISSUE THREAD

**Issue by nugsy** [ObliqueNET/Stratos#297]
The most recent post to #stratos-news on the discord said emerald blocks were made to be sellable, but they're not. :s 

![2019-07-21_22 55 43](https://user-images.githubusercontent.com/49658105/61609391-d550bf00-ac0a-11e9-9ae6-eeabea86412b.png)

**Comment by fatyg5** [comment]
Fixed. Was marked as "pixelmon:emerald_block" instead of minecraft:
