### ISSUE TITLE
I am still banned it says :(

### ISSUE THREAD

**Issue by Squldwerd** [ObliqueNET/Stratos#30]
Hi thank you for unbanning me. I got on today and saw that is wasn't unbanend thought so i was kind of confused. Is there any way you could unban me again please or fix this if you can. I think i am still banned on terra. which is the server i was last in and that might be why it says i am banned still.

**Comment by MrBritish8** [comment]
you should be pardoned. Unless something happened making you be banned again, you should be able to return to the server

**Comment by Rasgnarok** [comment]
@Squldwerd Last I checked I unbanned you, please reply here if it doesn't work for some reason.
