### ISSUE TITLE
Ultra Necrozma's extending horns

### ISSUE THREAD

**Issue by mairai** [ObliqueNET/Stratos#301]
![image](https://user-images.githubusercontent.com/50144595/61903369-f60a6480-aee9-11e9-9893-1ad6f3498c32.png)
![image](https://user-images.githubusercontent.com/50144595/61903446-22be7c00-aeea-11e9-860f-1d9bcdd45f59.png)
![image](https://user-images.githubusercontent.com/50144595/61903701-c90a8180-aeea-11e9-9574-41108040e2bf.png)
Both my Necrozma and big_cat_nug's Necrozma have horns that extend far into the sky. It doesn't seem to be an individual issue, as other players can see it as well.

**Comment by nugsy** [comment]
![32e105e46e17abe8ff96d4783bdf84d2](https://user-images.githubusercontent.com/49658105/61904132-0cf58a80-aedb-11e9-9e0e-d39800571955.png)
i asked the pixelmon support discord :X

**Comment by fatyg5** [comment]
Gonna close this because I personally fixed this for the next Pixelmon update so it should not be an issue whenever that releases.
