### ISSUE TITLE
Banned (IGN: Second_Entity)

### ISSUE THREAD

**Issue by UglyGods** [ObliqueNET/Stratos#304]
Hello, sorry for the trouble but around 6 months ago I was banned for the use of alts. I made an appeal that an admin later commented on asking for my username. https://github.com/ObliqueNET/Stratos/issues/73#issuecomment-499699246_
I never got to respond due to not checking on the status of the post after so many months. Hopefully it's not too late, my IGN is Second_Entity.

**Comment by Grassip** [comment]
All good, I will unban you now.
