### ISSUE TITLE
Polls 

### ISSUE THREAD

**Issue by Rasgnarok** [ObliqueNET/Stratos#305]
Can't click delete at all, 
![image](https://user-images.githubusercontent.com/18584380/62826943-f9ad1500-bb92-11e9-89c0-01b74f2f9c5e.png)

**Comment by Valjean42** [comment]
![image](https://user-images.githubusercontent.com/47981683/69489567-b39a6980-0e82-11ea-9ef1-3c12fb7846be.png)
Hmm, seems to work fine on my end

**Comment by Hiroku** [comment]
I fixed it a while back, forgot to close the ticket
