### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by Dynaster** [ObliqueNET/Stratos#308]
I apologize for using xray to try to find dungeons in game. Didn’t find any so I didn't get any advantages from doing it. 

Kind regards,

**Comment by Grassip** [comment]
You will still wait out the rest of the 1-day ban. If we catch you cheating again, it will be a permanent ban. We have removed everything that you used for xray for when you are back online.

**Comment by Dynaster** [comment]
So ill be able to play from the time i got banned yesterday? Also what “everything”

**Comment by Grassip** [comment]
The minecart contraption you had. And yes, you were tempbanned for one day.

**Comment by Dynaster** [comment]
Idk what you guys removed sorry, because I put it all in my chest before I got banned which was the minecart/rail. Just want to clear it up.
