### ISSUE TITLE
UNBAN ME

### ISSUE THREAD

**Issue by YTPenguinPlayz** [ObliqueNET/Stratos#309]

**Comment by fatyg5** [comment]
I see no reason why your race or what you were doing has to do with your ban. Our rules clearly state that doing things such as this are not allowed, and you broke that rule.

**Comment by YTPenguinPlayz** [comment]
> I see no reason why your race or what you were doing has to do with your ban. Our rules clearly state that doing things such as this are not allowed, and you broke that rule.

i think that ur gay

**Comment by YTPenguinPlayz** [comment]
im sorry how am i supposed to get unbanned? my friend is sleeping over and he typed all that im sorry sir

**Comment by YTPenguinPlayz** [comment]
im sorry how am i supposed to get unbanned? my friend is sleeping over and he typed all that im sorry sir

**Comment by YTPenguinPlayz** [comment]
im sorry how am i supposed to get unbanned? my friend is sleeping over and he typed all that im sorry sir

**Comment by YTPenguinPlayz** [comment]
im sorry how am i supposed to get unbanned? my friend is sleeping over and he typed all that im sorry sir
