### ISSUE TITLE
Im also Ban

### ISSUE THREAD

**Issue by ColinSpeight** [ObliqueNET/Stratos#31]
This is megawall, the other person who got banned, I don't think I said much bad, I was bored and wasn't listening to the mod when he told me to stop using caps because I was waiting for a legendary to spawn
I said just because i'm black once or twice which is a true statement and I really don't think I deserve a perm-Ban. Please Help

**Comment by Rasgnarok** [comment]
Hi megawall, can you recall to me what got you banned? I have slurs on the logs, but I'd like to hear your side of things.
