### ISSUE TITLE
pls unban me

### ISSUE THREAD

**Issue by YTPenguinPlayz** [ObliqueNET/Stratos#310]
im sorry i will never do that again i was playing with my friend and he told me to do that i did not know that it was brakeing the rules im sorry i have to go to sleep

**Comment by YTPenguinPlayz** [comment]
im jk my friends IGN is MooseSmellsNice

**Comment by CenizaRey** [comment]
It’s included in the rules of our Network that your account is your responsibility. And that’s _if_ we even choose to believe your story about your friend messing with your account. I could give you the benefit of the doubt, but I don’t really want to risk opening Oblique to someone of your insensitive character. For that reason, you will not be unbanned.
