### ISSUE TITLE
Banned from discord and the server 

### ISSUE THREAD

**Issue by NigerianSexGod** [ObliqueNET/Stratos#311]
Hello I was banned for stating my opinion never was I rude to the staff members. all I was doing was trying to discuss my matter. my friend had got banned for saying N****, as he was new but just joined had no idea and said whats up my n**** to me. he was told he cant say that then he got banned.. after he apologized. And the issue is I have seen other people say it and get warnings. but he got banned right after being warned but my friend is also black and in his culture it meant it in not a racist way. but this is my appeal I was stating that I have a right to stand what I think is wrong and when staff member is telling me I am not aloud to bring it up with a higher staff member? and then bans me from discord after saying... so I get on the server and PM a staff member saying would you rather have me talk on discord then in game. and I got banned on the server to. This is my appeal I will apologize and leave my issues of the server and in game I really feel I did nothing wrong I was never vulgar or rude. I got banned for stating my opinion. What I think is a non valid reason for a ban. IGN: NigeranSexGod

**Comment by Grassip** [comment]
You not only pestered staff and argued with them excessively, but attempted to bypass your ban by arguing on Terra and on Discord as well. You were given warning and continued to argue nonetheless. You will not be unbanned.

**Comment by NigerianSexGod** [comment]
> You not only pestered staff and argued with them excessively, but attempted to bypass your ban by arguing on Terra and on Discord as well. You were given warning and continued to argue nonetheless. You will not be unbanned.

I went to the other server to ask where to appeal for a unban ?

**Comment by NigerianSexGod** [comment]
> You not only pestered staff and argued with them excessively, but attempted to bypass your ban by arguing on Terra and on Discord as well. You were given warning and continued to argue nonetheless. You will not be unbanned.

Is there any other way to get unbanned I have spent quite a bit of time on the server and Enjoy it
