### ISSUE TITLE
Ban Appeal apology 

### ISSUE THREAD

**Issue by NigerianSexGod** [ObliqueNET/Stratos#312]
As I said before I apologize for my mistake.. I spent a lot of time and energy on this server. If I was given another chance I can promise I will not bother staff anymore I just was trying to look out for my friend. as in your quote I just went to the other server to ask where to appeal because it was not given in the ban Message I also was banned on discord before so I couldn't try to bypass . I sincerely apologize. I just got a little mad and caught up in the moment. I can guarantee you will not here an issue from me again. I am a daily player that puts a lot of time and energy in with daily votes. thank you for your time.    

"You not only pestered staff and argued with them excessively, but attempted to bypass your ban by arguing on Terra and on Discord as well. You were given warning and continued to argue nonetheless. You will not be unbanned."

**Comment by NigerianSexGod** [comment]
If there is any way I can get unbanned it would be appreciated

**Comment by Grassip** [comment]
You have been given your answer, you will not be unbanned. Please do not post anything else on here.

**Comment by NigerianSexGod** [comment]
Alright thanks for your time...
