### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by ThigHighSockss** [ObliqueNET/Stratos#314]
Well, let me start off by saying 1. I never called anyone an idiot 2. I JUST joined the server and started a town 3. Who would this "Sahv" person be 4. Why did I get banned? and what does this have to do with me? I've literally done nothing on the server to date my first day of joining was today and I want a reason, a logical well thought out one as to why I was banned.

**Comment by fatyg5** [comment]
It's very quite obvious from the way you were acting, plus the fact that your friend, Jkaem, has made a ban appeal the same day you join the server and my staff team immediately was able to connect two and two together. It's even more hilarious that you magically started our server today, but amazingly!!! got banned from our server AND Discord with no ban appeal link, yet you immediately found the tracker to post ban appeals! Congratulations and enjoy your ban!
