### ISSUE TITLE
Talos Gym Shards Mega Thread - Refunds

### ISSUE THREAD

**Issue by MMGDoogz** [ObliqueNET/Stratos#315]
For all players who have been doing the gyms before the newest addition into the game with the Talos Shards there is no current way to get the shards for the gyms you have already completed. I will be refunding all players who show proof, (IE, screenshot of your badge case) the amount of shards you were supposed to get. 

Please post with your IGN and screenshot to get refunded!

**Comment by lolsikinz** [comment]
I'm owed 120 shards according to /gyms
IGN: lolsikinz
![2019-09-03_01 37 57](https://user-images.githubusercontent.com/9399603/64135794-b1c58a80-cdec-11e9-8db1-84ce914ebebf.png)
