### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by zeddaboss** [ObliqueNET/Stratos#317]
I realize that what I have done is wrong, I did not properly read all the rules that were provided and hence did not realize that using an alternate account was a bannable offence. Although I did use a Alt. account I did not benefit much from the account other than the money I acquired, the masterball I received and the rare candies plus a shiny. I have spent a lot of time playing on this server due to its welcoming society and have greatly invested myself into the community. I tried to be the best person I could be. I had no ill intentions of having an advantage over anyone else and regret my actions.

**Comment by zeddaboss** [comment]
I hope you guys could reconsider this ban and will never do anything against the rules again if given a second chance.

**Comment by Grassip** [comment]
We are going to shorten your ban to 2 days. If we catch you breaking the rules again, your ban will be permanent.
