### ISSUE TITLE
Un-Ban 

### ISSUE THREAD

**Issue by Amazingfunbx300** [ObliqueNET/Stratos#318]
Hello my name is Tony and my english is not good. Thus, I typed all the text in google translator.

My real problem is that I was banned because I did a miss-click. Jmd needed help with chat regarding Stratos. He needed a master ball and I wanted to help him and, as mentioned above, accidentally defeated this Pokemon so it disappeared. I am very sorry, but I would not have expected such a reaction without great support or the like to get a ban for 24 hours.

I would ask you to reconsider this and give me another chance.

I'm so sorry, I just wanted to help.

Sincerely, Tony
 ingame: Crazy_Nuts_

**Comment by JettisonedGames** [comment]
While we understand that it was likely an accident, a critical rule on the server was broken.  You also lied to staff and were not cooperating until it was clear that we knew what you were saying was not true.  We discussed this among ourselves, and it was decided that a 24 hour ban was warranted.  It will remain a 24 hour ban, beginning at the time it was given.
Respectfully, 
JettisonedGames
