### ISSUE TITLE
KFC_chicken_ banned 

### ISSUE THREAD

**Issue by KFCchicken786** [ObliqueNET/Stratos#319]
i got banned for a theft of a legend .
first i saw a wild Zekrom and a player that was afk. ( i know its the player's Zekrom) but they logged off , then like four people appeared and tryed to catch it , so i took a masterball and caught Him 
( to prevent them from take it) . I know what i did is wrong i wont do it again and im sorry . 
ill delete him please unban .

**Comment by CenizaRey** [comment]
We know through checking the logs that you ran several warp commands between the Zekrom spawning, and you capturing it. Your claim that you coincidentally bumped into the pokemon is a lie. You actively went after it. Secondly, you claim that "like four people appeared"; this is also a lie. And finally, this is not the first time you've been caught stealing legendaries. For these reasons, you will not be unbanned.

**Comment by KFCchicken786** [comment]
i didnt say that i coincidentally bumped into the pokemon i tp to my set home there , and someone realy tryed to take him .

**Comment by Grassip** [comment]
Hi KFC, after examining the logs, I am give you another chance and let you back online. Know that what you did was still wrong and that you should leave the legend be if it was not spawned on you, and that if you are caught stealing a legend again we will ban you permanently. I do ask that you delete the legend that you caught immediately when you log back on, and we will be checking to make sure you have done so.

**Comment by Grassip** [comment]
Hi KFC, after examining the logs, I am give you another chance and let you back online. Know that what you did was still wrong and that you should leave the legend be if it was not spawned on you, and that if you are caught stealing a legend again we will ban you permanently. I do ask that you delete the legend that you caught immediately when you log back on, and we will be checking to make sure you have done so.
