### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by IBXDoge** [ObliqueNET/Stratos#32]
Dear staff, 

I was ban around November last year. I joined the server with the mind set of being a dummy and getting ban, but the reason I did this was because I was dared to get ban on a server that I don't use.  Although here I am now trying to play this really good pixelmon server that I underestimated. I hope you see this appeal and considerate un-banning me.

Thank you for your time, hope to see you on the server! (my ign is IBX_Doge)

**Comment by fatyg5** [comment]
The ban was in July, not November, but I'm unsure of what the exact ban reason was. Either way, you'll be given an unban. Do not cause trouble.
