### ISSUE TITLE
Dunno if this is the right place but, My Ban appeal? Ign: TechnosToxicity

### ISSUE THREAD

**Issue by Oshirisu** [ObliqueNET/Stratos#320]
To be honest, I was in the wrong for having a go at Hawky for past crap but Permanently banning somebody for that is a bit, well, excessive don't ya think? I will admit I've had my fair share of previous incidents, 2 or 3 I believe. For all of those I was punished accordingly, 1st with a note 2nd 3 day ban 3rd Blacklist from staff later removed, who knows why, but what I'm saying is a Perma ban removes the opportunity for change does it not? Removing that opportunity removes the chance for growth does it not? In the long run you can blacklist me from staff and events if you want but permanently banning somebody for addressing a long time issue between me and Hawky which was sorted by a lovely block from the chap feels a tad over the top. Seeing as I'm being bunched in with the excessive extreme rule breakers. 

I give people second chances because giving them that second chance opens their eyes for change, I give people second chances because everyone deserves a second chance. Think what you will of me but again, banning somebody for addressing an issue between that player and somebody else is fine but permanently banning them for that is just over the top. Rudeness is usually met with a mute, not usually a ban y'know?

Back to my 2nd watching of Brooklyn 99, again thank you Rasgnarok for the brilliant recommendation that is this show. - TechnosToxicity

P.S if this was my last time on the server then I wish for a last request if it is, and only will be spoken if it is. Cya

**Comment by Oshirisu** [comment]
Side note, now banned from the discord too

**Comment by JettisonedGames** [comment]
You have a long, extensive record of offenses on the server, mostly pertaining to offenses in your interactions with other players. You have been warned multiple times for this, and you still picked a fight with a staff member by bringing up past transgressions. Taking this into account, you will not be unbanned.
I posted on the wrong issue initially, so here it is officially.
