### ISSUE TITLE
Stratos Appeal (alternate accounts)

### ISSUE THREAD

**Issue by ii-destroyer-ii** [ObliqueNET/Stratos#322]
-the two accounts were made by my brother for him and friends to play on (one for him).
-I am merely related to him and... we live together (under 18).
-I showed them the server to try and acquire the invitefriend thing, but forgot about it.
-The second account joined was the only unblocked one.
-We merely wish to rival each other and see who is the most skilled.
-They are independent from their town (side-by-side to judge) through to their Pokemon battles and luck with battles.

-And the alternate accounts rule was not seen in server/out of server, and I apologise if there was.
-Certain other players can verify that I did not create those two accounts.
-Please list how this could be fixed...

**Comment by Grassip** [comment]
I'd like to discuss this through discord with you to clear some things up before making a final decision on what account gets banned. Please message me, my discord name is Grassi#2840, you can also find me under the lead tag in the oblique discord.

**Comment by fatyg5** [comment]
It's been a month. Closing this
