### ISSUE TITLE
banned for underpricing legends

### ISSUE THREAD

**Issue by Fasuh** [ObliqueNET/Stratos#323]
hello, 
i've got banned recently for underpricing legends, i've sold an entei for 15k, the thing is, in my opinion its a good price since it had like one of the worst abilities - docile and a bad IVs, the guy who bought it sells it now for 20k which i dont think differs that much either, also entei is a really common and weak legendary so i feel like i was right with the price, im sorry if thats not the case and i misvalued it. it is correct i've got warnings before cuz i didnt know it was that big of a deal, legends i've sold arent particularly popular and had bad stats/natures so i've sold them cheap not knowing it was bad before the warnings.
Again sorry for the problem and thanks for reading.

**Comment by JettisonedGames** [comment]
You have received 2 warnings before, including a Regirock for 15k PokeDollars, as well as an Entei for 5k Pokedollars.  You had also already been informed of the price on an Entei before selling this newest one for an undercut price.  Your ban will stand, but it will expire tomorrow at 1:08 PM Est.  You can always ask a staff member or the general player base if you are unsure of the price of something.
