### ISSUE TITLE
Ban appeal Doniux22

### ISSUE THREAD

**Issue by Doniux22** [ObliqueNET/Stratos#327]
I have been banned on the stratos server pretty long ago, because I was using xray on the server.
Now I don't know how long, but it has been a while I would really like to get another chance. I've never been banned before and really enjoyed my time on the server. I give you my word I don't have xray anymore in the mod folder, so can I please have a chance again.

I look out to your response,
Thanks

Doniux22

**Comment by JettisonedGames** [comment]
We will offer you another chance, so long as it doesn't happen again.  Another x-ray offense will be a permanent ban.  Welcome back to Oblique.
