### ISSUE TITLE
Ban Appeal Pokeman508

### ISSUE THREAD

**Issue by pokeman508** [ObliqueNET/Stratos#328]
I dont really understand what I did. I thought I had lost a box so i told the staff online and then after a few minutes I was banned for lying to staff about losing it. It had said I was hiding the items but I really didnt know where the items were.

**Comment by Grassip** [comment]
You were tempbanned for one day because you hid your items from your dexrank kit underground behind a picture frame, and then pretended not to know that it was there. There's no way you could have forgotten where these items were or not have intentionally hidden them when they were in this spot, underground:

**Comment by Grassip** [comment]
![image](https://user-images.githubusercontent.com/47408346/68625319-d7cf7100-04a6-11ea-812c-2645254be1a7.png)

**Comment by pokeman508** [comment]
I didnt build that room? My brother built that room

**Comment by pokeman508** [comment]
Was the box inside?

**Comment by pokeman508** [comment]
Is there anyway for me to prove this? I really hadnt known it was even in there

**Comment by Grassip** [comment]
What is your brothers IGN?

**Comment by pokeman508** [comment]
Pokeman9999

**Comment by Grassip** [comment]
when was the last time you had the box? did you place it in a chest somewhere?

**Comment by pokeman508** [comment]
No I had it earlier today and I had placed in my base

**Comment by pokeman508** [comment]
Last i was was was around 2

**Comment by Grassip** [comment]
Okay, we will unban you. Sorry for the misunderstanding, next time please make sure you two communicate and don't hide things from each other.
