### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by pavlikovic06** [ObliqueNET/Stratos#329]
Hello i got ban today for x-ray but i dont have any x-ray installed in technic and i dont ever use a x-ray

**Comment by fatyg5** [comment]
Alright, I'mma be straight with you. We have found multiple tunnels dug by just you leading in odd directions directly into dungeons/spawners to chests. Are you sure you want to deny this?

**Comment by pavlikovic06** [comment]
i was using joruney map underground map i though its not some hack

**Comment by JettisonedGames** [comment]
After discussion among our moderation team, with the evidence we have, you will not be unbanned.
