### ISSUE TITLE
Misunderstoodly Banned

### ISSUE THREAD

**Issue by GarbTheKId** [ObliqueNET/Stratos#33]
IGN: ArcherMark
So basically I got Banned for Town Griefing... I forgot when but it was like a week ago when I realized that my PC was stolen, the only other person I know that was on often was WickedShadow498 and he had just created a new floor for his breeders, so I went over and took his PC... a day or so later one of our Public PCs was missing and it was one that I made because I was technically the builder in our town. So I looked in our discord server and it WickedShadow said that he took the PC 
![general - discord 2019-01-05 10_11_35 pm](https://user-images.githubusercontent.com/28632847/50731592-eb97a180-1136-11e9-8d50-9ddcc322107c.png)
So I took it and replaced it back. I know I shouldn't have tooken his PC the first time so I am very sorry. I already apologized to him, But honestly I dont think that taking 1 easily made block should be bannable for "town greifing" I hope you understand and unban me.

**Comment by fatyg5** [comment]
3 day tempban should be nearing its end in a day or so. Will be unbanned then.
