### ISSUE TITLE
Darm43 Ban Appeal Stratos Server

### ISSUE THREAD

**Issue by Darm43** [ObliqueNET/Stratos#331]
I was banned for alt accounts because I just downloaded technic and my friend who is already on the server was with me helping me download it. Then when I joined the server one of his friends who is in my friends faction. He said it was him so he would know to its him and to send me and invite to the faction because my friend did not have his computer with him to be able to log on and invite me. He was on my computer typing to his friends saying it was him so that I would get an invite to the faction. Could who ever is able to unban me from Stratos please if you would.

**Comment by Grassip** [comment]
All good, we will unban you. Sorry about the misunderstanding!
