### ISSUE TITLE
Ban appeal

### ISSUE THREAD

**Issue by LjMadGecko** [ObliqueNET/Stratos#332]
Imma be honest, I did hack and I feel kinda bad now. Deep in my hart I knew this was gonna happen and I needed it. I have deleted my hacks ,but if you could please don't make this permanent. :c ngl this is first time I have ever been banned on mc and 5 of my friends are playing on this server so I feel like a can't leave them or make them play another server when I'm playing cuz of me. what I did was stupid

**Comment by Grassip** [comment]
Alright, well thank you for being so sincere about it, I've decided we will change your ban to a 3-day tempban. If you break the rules again, we won't be so lenient, so please be sure to read the rules in /rules when you join back, and try to think before you act next time. Have a good night \o/

**Comment by LjMadGecko** [comment]
thank you
