### ISSUE TITLE
Banned for cloning mons?

### ISSUE THREAD

**Issue by MattBlower835** [ObliqueNET/Stratos#333]
So woke up this morning to find I've been banned for cloning mons when I was a wild card. And I want to confirm this is 100% false as I actually never had wand perms when I was wild card and had to get Polylogue to make my gym teams, he can confirm this. So I would like to know what proof there is of me cloning mons and if so how it was done.

**Comment by Rasgnarok** [comment]
As discussed with Hiro, it really has come down to continued lying that makes us not believe the word of mouth - whether you say it is not true does not make it evidence. Having no trust left to spare, I am honestly not able to help but doubt what you say. The ban remains. I legitimately wish you no wrong.
