### ISSUE TITLE
KoroSamurai and TitaniaNova Ban

### ISSUE THREAD

**Issue by KoroSamurai** [ObliqueNET/Stratos#337]
We are husband and wife and live in the same house. We are not using ult accounts we are 2 different people. You can even watch her stream to prove we are 2 people 
https://www.twitch.tv/titanianova

**Comment by JettisonedGames** [comment]
Sorry about the misunderstanding.  Thanks for providing the Twitch link for the verification so we were able to get this resolved quickly.  We hope you enjoy your time on Oblique.

**Comment by Rasgnarok** [comment]
I am really sorry this ever happened, @KoroSamurai . Closing this now as it was resolved, but for the record, there should have been no ban had it been alts either way. That rule only applies if you abuse one-player-one-reward priviledges, which you didn't anyways. Extend my apologies to your wife, and happy playing
