### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by just1NY** [ObliqueNET/Stratos#338]
I was banned for xray, but I literally didn't even do anything.
Plz un-ban - just1N_Y

p.s literally happened while offline. What's up with that?

**Comment by ben4235** [comment]
This is one of my towns members, after searching and going through multiple servers this is the only server that didnt suck ass. None of us would want to cheat especially on a perfect server. plus he was offline lol and didnt even mine today. We just wanna game some pokemon minecraft :)

**Comment by Grassip** [comment]
Hello, yes, you were banned because you have an x-ray mod on your client. All you have to do to get unbanned is provide screenshot proof that you have removed it from your client, and we will allow you back online.

**Comment by just1NY** [comment]
Heres my proof I guess
[
![Capture2](https://user-images.githubusercontent.com/58381752/69910222-8ba48c00-13d5-11ea-9c26-2fec5c9f2344.PNG)
![Capture1](https://user-images.githubusercontent.com/58381752/69910223-8ba48c00-13d5-11ea-8192-4c7bdb36423b.PNG)

](url)
