### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by NicK9899** [ObliqueNET/Stratos#340]
I was falsely banned for having alternate accounts. This is a misunderstanding as the second account that your anti-cheat detected was my brothers. My brother saw me playing pixelmon and wanted to try it out for himself, while he was playing i had forgotten to close my game and i was still in the server. After about maybe 1 or 2 mins at most of playing he got kicked to the main lobby where you choose which server you want to play on and it said "Alternative Accounts" in the chat. If you unban me i will be more careful with this in the future and i promise that it wont happen again. I sincerely apologise for this trouble.

/NicK

**Comment by fatyg5** [comment]
Ah yes, your brother, I see. You happen to have 7 brothers by chance? Because our Anti-cheat doesn't magically detect 8 accounts on the same IP.
![Brother](https://user-images.githubusercontent.com/8277657/70851838-7b29f200-1e68-11ea-9e95-6c8d623da2fc.png)

**Comment by NicK9899** [comment]
I believe that those are some of my alt accounts that i used for pixelmon months ago. I dont remember going into Oblique with those although i probably did. Im pretty sure that i went into servers to troll people by starting conversations (ik it seems weird) Anyways i hope that you can look passed this and give me a second chance because as i said it wont happen again.

**Comment by Grassip** [comment]
I will give you a second chance, but if we catch you abusing the alts on your ip we will reban.

**Comment by NicK9899** [comment]
Thank you i am so greatful :DD
