### ISSUE TITLE
mitosis702 ban

### ISSUE THREAD

**Issue by mitosis702** [ObliqueNET/Stratos#341]
So I'm kinda confused, me and Chris got in kind of an argument  but I didn't really think it was that big of a deal, and everyone kinda put the blame on him for being too intense and taking it too far, and even a little later on grassi came on and messaged me asking if I was okay and that how Chris handled it was unacceptable, etc., So I just made the obvious conclusion at that point that I wasn't in any trouble. But then out of nowhere with no warning at all I got kicked and it said I was banned for "hindering chat". Is this some sort of mistake? Can I get this appealed, or if it's not a mistake can I get an explanation please? Thank you

**Comment by Grassip** [comment]
Hi mitosis, sorry about the confusion. Do you mind messaging Ras on discord? She will explain it all to you.

**Comment by Rasgnarok** [comment]
You've been unbanned based on the poor reasoning for the ban in the first place. My apologies Mitosis, I hope you and Lua don't get into this again.
