### ISSUE TITLE
Warriorexcile8 Ban

### ISSUE THREAD

**Issue by warriorexcile8** [ObliqueNET/Stratos#343]
Okay so i met this girl and she's a helper, super nice super fun to hang out with right, she was drunk and i was hella bored so i joked around with her to see what she would say and i said send noods u know cuz i was joking ryt and she obviously didnt okay. The next day i voted and i unboxed a shiny poly and she was like omfg lucky, and she told me its like super rare because i am kind of new to pixelmon so im still learning and she said she wants it so i was like bet, so i was like ill trade u, then she asked what for and i jokingly said a special pic xD

after i said that she told me "im not that type of a girl" so i was like okay lmfao and then the next day i tried logging into pixelmon and it said i have been banned... ban reason: This is minecraft

like tf??? over joking in discord i got banned on the server... 

im a youtuber and i was making a series with Thedarklord because we are both youtubers and i have almost 4k subs and we have made around 4 episodes so far but have yet to post because i have to edit all the videos and shorten etc... so anyways in short i got banned for joking with a helper in discord chat and now i cant record the series. GG

came to learn about pixelmon and share the server and help promote the server but instead since i joked with a helper about noodes i get banned which seems real unfair.

guess i need to choose who i talk with more carefully since helpers will ban me if i make a joke.
learned my lesson. never try to joke with a helper. Anyways i think i was wrongfully banned. up to you if i get unbanned. if i dont get unbanned then i guess it saves me time from trying to promote the server and editing time. A friend reccomended me to join this pixelmon server because he said its pretty chill, so i hope i do get unbanned because from what ive seen so far it is a cool server. i captured a legendary on the third day with the help of dynaster (Really nice guy), And 4 shiny's so far.

Anyways again its up to you if i get unbanned. glhv

**Comment by warriorexcile8** [comment]
i wish to speak to the owner of this server.

Please link me the owner's discord or social media platform in which i can contact them.

**Comment by Hiroku** [comment]
Asking a helper for nudes as a joke one-time is something I could understand. Making the same joke again the next day... I'm pretty sure I know what you were motivated by and it wasn't just a joke. Trying to pull the YouTuber thing like we have something to lose, while simultaneously making no apology for making that helper uncomfortable, means I'm not interested in unbanning you. I am one of the two owners, so you needn't worry about finding a way of contacting us.

**Comment by warriorexcile8** [comment]
she never told me she felt uncomfortable. and yes it was  a joke.  Just because you do not know me does not mean you know if im joking or not. my personality is different from yours. if someone tells me they are uncomfortable then i stop. but she never did not once. and im not trying to make it like you're losing something. im just informing you that ive been recording episodes on you're server because now i wont be able to.

**Comment by warriorexcile8** [comment]
Why would i apologize when she never told me she felt uncomfortable? and why do you care so much? the conversation between her and i was between the two of us. and since i joked with her and talked to her hinting at nudes you decide to ban me? what kind of system is that?

i was not ever going to trade her the pokemon for anything out of game. it was 100% a joke about nude. she never told me she was uncomfortable and never hinted it either. she laughed so how tf was i supposed to know if she feels uncomfortable?

**Comment by warriorexcile8** [comment]
i Will screenshot the entire chat and send you proof that i was joking. how can i direct message you?

**Comment by warriorexcile8** [comment]
you deleted the comments....

**Comment by warriorexcile8** [comment]
![image](https://user-images.githubusercontent.com/59759715/72201091-81d36700-341e-11ea-869e-2fbfd69c399d.png)
![image](https://user-images.githubusercontent.com/59759715/72201107-b2b39c00-341e-11ea-8746-8081accd8f91.png)
![image](https://user-images.githubusercontent.com/59759715/72201112-c0692180-341e-11ea-822c-2eed8c427bf3.png)
@Hiroku 
heres evidence i was joking.

**Comment by Hiroku** [comment]
I mean come on; you make the same joke about getting nudes from a girl on a Minecraft server twice in the space of a day. You can't convince me that it was just a totally aimless joke on both occasions. I know teenager creeping when I see it. Also, you call that evidence that you were joking; I call that evidence that _you said_ that it was joking. Are you trying to tell me that if she instead had giddied up and decided to send you nudes, that you'd have said 'no no, I wasn't being serious'? C'mon.

You're also not the first person to mention some ethereal YouTube videos / Twitch streams in a ban appeal. Please don't take me for a complete idiot; I know what manipulation looks like. 

In any case, even if they were both totally not serious and entirely jokes (and we both know they weren't!) then you would still have been wise to apologize for making inappropriate jokes. And if you don't think asking for nude pictures of underage staff is an inappropriate joke then that is very disturbing indeed.

**Comment by warriorexcile8** [comment]
LOL OMFG, i honestly was joking. you literally are so closed minded you cant think past what you know.



underage?!?!?!?!?! what?!?!?!?! she lied to me then...

**Comment by warriorexcile8** [comment]
ill apologize now holy f. why would she lie to me about that though...

**Comment by Hiroku** [comment]
Actually I was wrong about her being underage. Must be thinking of one of my other staffers. Thought she was 16-17 which means I was probably thinking of a specific other staffer. Well anyway, doesn't change the thrust of what I said, so I'll just concede she isn't underage and leave it at that.

**Comment by warriorexcile8** [comment]
well i wasnt joking about the youtube either. i am being 100% serious... i can even prove it by linking my channel and send you the unedited first through 4th episodes to prove i seriously did record a series. its not manipulation... anyways and to answer your first question that if she giddied up and decided to send me nudes, i still would not have given her the pokemon. because 1 it was a joke, and 2 i dont trade ingame items ever. i may joke sometimes but i never actually do it.

**Comment by warriorexcile8** [comment]
otherwise if i did trade ingame items for stuff like that i would have gotten banned from 90 other games by now... im rich in many games. not pay2win but i farm the hell out of games.

**Comment by warriorexcile8** [comment]
this was my first minecraft series ever on my channel, havent uploaded any episodes ( Again its because i havent edited them, first vid is like 4hours long, 2nd one is like 2hours etc its going to suck... anyways i can send proof if u want. but it wont matter in the end if i dont get unbanned.

**Comment by warriorexcile8** [comment]
![image](https://user-images.githubusercontent.com/59759715/72201457-315e0880-3422-11ea-8ddd-d0c543a3723d.png)

**Comment by warriorexcile8** [comment]
i actually live streamed an episode, let me check if i can find the link, this will also prove my series.
here we go: https://www.youtube.com/watch?v=IQ-zrvRh980
https://www.youtube.com/watch?v=uPXuRQqzPLA

**Comment by warriorexcile8** [comment]
i havent live streamed in months so i wont get many views till i live stream some more. but anyways i apologized to her. idk wht 2 do now.

**Comment by Grassip** [comment]
Hi there,

I believe that both of the owners clearly understand that you do indeed have a Youtube channel and that you did in fact enjoy playing on Oblique, so there is no need to continue to give us prove of that. Even if we were going to unban you, which we aren't, you still refuse to apologize for your actions. You will not be unbanned and that is the end of it. And stop trying to prove that you are a youtuber, we honestly don't care.

Grassi

**Comment by warriorexcile8** [comment]
um... i just said i apologized..

**Comment by warriorexcile8** [comment]
@Grassip i literally apologized...
![image](https://user-images.githubusercontent.com/59759715/72201514-e85a8400-3422-11ea-8353-9cd43cd3eb29.png)

**Comment by Grassip** [comment]
Okay, thank you for apologizing to her. I apologize for not including that in my message, I happened to post it 7 seconds after you posted yours admitting that you have apologized. Either way, this is over now.

**Comment by warriorexcile8** [comment]
so in the end i joked with a helper, got banned, pleaded with owners it was a joke, pleaded because im doing a series on the server, and apologized to her even when she didnt ask for an apology, and still not getting unbanned? @Grassip

**Comment by fatyg5** [comment]
Correct.

**Comment by warriorexcile8** [comment]
1. You all are Petty as Fuck
2. The staff Team are immature and cant handle a joke
3. Owner needs to grow a pair 
4. Hope you have DDOS Protection that can handle NAZZER

**Comment by fatyg5** [comment]
Alright, thank you, have a good rest of your life

**Comment by warriorexcile8** [comment]
this ddos protection is garbage :,D 
![image](https://user-images.githubusercontent.com/59759715/72201640-315f0800-3424-11ea-9b03-b91290d81112.png)
