### ISSUE TITLE
Ban request.

### ISSUE THREAD

**Issue by Leonidas9798** [ObliqueNET/Stratos#348]
The ban appeal that was sent in before was not sent by me, apologies. someone else seems to have gotten control over my account briefly.  Matt blower was not the target reason for my ban. I'm going to disregard everything Grassip said in response due to invalidation and hope no one was bothered by the random odd post. It was never my intention to get unbanned certainty not for a server with staff such as your own. Again I do apologize for the inconvenience and wish you all well.

**Comment by Grassip** [comment]
Not sure why you opened a new thread for this but thanks for the clarification. Have a nice day :)
