### ISSUE TITLE
xNAMMOx banned

### ISSUE THREAD

**Issue by xNAMMOx** [ObliqueNET/Stratos#350]
I was banned for fly / speed hacks, I played on this server for about 5 days before I was banned, I am guilty on all accounts but I would like to try to plead for you forgiveness.  This was the best Pixelmon server I found, and I tried a lot of them. I really love the no pay to win aspect of this server, for I am very poor. The only reason I was cheating was to try to catch up to the rest of the players who have been playing for a long time, and I realize that this was wrong. For all my wrong doings I am willing to give up all of my items and Pokémon just to play on this great server again. I promise that I won't cheat anymore. You can even have staff members periodically check on me. I just really love the community and everyone was really friendly to me the short amount of time I was online. Please consider unbanning me from your amazing server, it would be much appreciated. Thank you! ~xNAMMOx

**Comment by Grassip** [comment]
Hi there! I've decided to let you back on due to the fact that you were sincere about this. Please make sure all cheats are removed before getting back on the server, and have a nice day!

-Grassi
