### ISSUE TITLE
Intulect Ban

### ISSUE THREAD

**Issue by intulect** [ObliqueNET/Stratos#351]
I was recently banned for selling legends too low and disrespecting staff, I apologize for my actions and will not take part in such activities again, I wasnt trying to be rude aswell, I simply stated I had work and didnt have time to discuss at that given moment, but again, I sincerely apologize for my actions. I shouldnt have gotten flustered when approached by staff. If the 2 days is mandatory to be carried out I completely understand but id like to rejoin my friends if possible, to save from future issues I will refrain from selling legends completely, as I dont quite understand the rule completely although I understand where I went wrong.

**Comment by intulect** [comment]
I was simply just a newb trying to make a quick dime, didnt realize it was that big of a deal but now I do

**Comment by Rasgnarok** [comment]
I've reviewed your ban affairs, and in my fair opinion, staff here made a huge mistake. It's getting corrected as we speak and I am investigating the roots of it, but long story short, you got banned for no rule whatsoever. That's staff abuse. For context, you can sell your legends however you want, just don't dump them for 1$ and call it a day. I don't think you wanted to do that anyways, so the clarification here is more for my staff, not for you.

You will be unbanned shortly, and if you can, I'd like you to direct message me on Discord, https://discord.gg/B3XcYcR  @Rasgnarok#6969.

**Comment by intulect** [comment]
Thankyou so much, i was confused as they said I was ruining the economy but i didnt understand how

**Comment by lolsikinz** [comment]
Hi, I firstly want to apologize for banning you and also want to explain a bit as to how this mishap occured. A lot of us staffers have been taught by old staff members about supposed "unwritten" rules but still not being told exactly what it meant. The rule in question has recently been removed. And again sorry for the mishap, hope you'll still have fun playing on Oblique. <3
