### ISSUE TITLE
appeal

### ISSUE THREAD

**Issue by dogeiscool123** [ObliqueNET/Stratos#353]
I got banned for being "racist" apparently, I don't really know what that means or how I could've been racist. If I DID do something racist, I'm sorry and I didn't mean whatever I said. I would like to be unbanned because I like this server and I don't want to change servers. I'll make sure not to make any "racist" remarks in the future if I'm unbanned.

**Comment by Hiroku** [comment]
![image](https://user-images.githubusercontent.com/1784721/75197135-44961f00-57a9-11ea-8f8b-b36f342b0f23.png)
You're saying you didn't know what you were saying here?

**Comment by dogeiscool123** [comment]
doesn't answer the appeal

**Comment by Grassip** [comment]
The answer is no, you are not getting unbanned.
