### ISSUE TITLE
Ban Appel

### ISSUE THREAD

**Issue by commanderhappy101** [ObliqueNET/Stratos#356]
Me Commander_happy Got Banned For Saying the nword I would Like to Be unbaned From Stratos 
I Will Try to refrain From Doing to again.

**Comment by fatyg5** [comment]
This ban appeal has almost no content nor do you seem to feel sorry for what you did. "I will _try_ to refrain from doing it again" isn't enough to convince me you're worth unbanning.

**Comment by commanderhappy101** [comment]
Yes I am sorry For what I did I Wont Do It Again I Promise
