### ISSUE TITLE
Stratos Market - Normal Scyther sprite shows as shiny.

### ISSUE THREAD

**Issue by Polylogue** [ObliqueNET/Stratos#38]
![Scyther1](https://imgur.com/uZnPGFm.png)
![Scyther2](https://i.imgur.com/mABbt8a.png)

Regular Scyther shows up as shiny in the #Stratos-Market channel on Discord.

**Comment by Hiroku** [comment]
This is a bug with Showdown. Below is the code I use to get those sprites. This should be reported to the showdown people!
![image](https://user-images.githubusercontent.com/1784721/51314974-dad31e00-1a9c-11e9-84d6-668b6b37e6d5.png)

**Comment by fatyg5** [comment]
Just, an update, have reported this to showdown
