### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by DylexicDonkey** [ObliqueNET/Stratos#4]
I was permanently banned by rowlette a couple weeks ago just before she got banned for admin abuse. I think it was unfair for it to be permanent and I was wondering if I could maybe get a second chance. I really enjoy playing on this server and I would greatly appreciate it if I could get unbanned.

**Comment by lolanonymous** [comment]
You have been given a second chance because after internal review we decided the stealing of apricorn rule was dumb. Unbanned.
