### ISSUE TITLE
Stratos Market not giving me all my mons.

### ISSUE THREAD

**Issue by MattBlower** [ObliqueNET/Stratos#43]
Bought 3 pokemon off of the discord market at 19:55 GMT but only recieved 2 of the mons to my party. I didnt recieve the Shiny Slowbro that I bought first, but recieved the Ash Greninja and Shiny Skarmory
![discord_2019-01-16_21-30-31](https://user-images.githubusercontent.com/37549563/51279912-40a8a280-19d6-11e9-92f6-9b2857372196.png)

**Comment by Rasgnarok** [comment]
If this is still an issue, open a new ticket since storage fixes.
