### ISSUE TITLE
bann appeal NopeyTheBear

### ISSUE THREAD

**Issue by NopeyTheBear** [ObliqueNET/Stratos#48]
don't know why it says i duped but i didn't so yhea

**Comment by NopeyTheBear** [comment]
could i see the proof and if it is the chests that are full of lott i found that in a random base and my friend can confirm this

**Comment by NopeyTheBear** [comment]
i am very sorry for taking the stuff out of the unknowns player base i didn't know that you couldn't take loot from unclamed bases i will try to return everything that i found there

**Comment by NopeyTheBear** [comment]
so will i loose my shiny and size voucher  cuz i got thos from my market keys that i bought today

**Comment by Rasgnarok** [comment]
To be clear, you also said this: 
![image](https://user-images.githubusercontent.com/18584380/51804487-a47d6780-222f-11e9-9266-99ffbd4e30da.png)

Which after 5 years of running a server, I can tell you is impossible. So how much did you lie exactly?

**Comment by NopeyTheBear** [comment]
it was a visual glitch i think it's gone now

**Comment by NopeyTheBear** [comment]
it was on the terra server where i had nothing

**Comment by NopeyTheBear** [comment]
and if i trew my pokeballs and picked them up it showed up as that

**Comment by Rasgnarok** [comment]
Anything else we should know about the rules you've broken?

**Comment by NopeyTheBear** [comment]
so there is a glitch and it's my fault ?

**Comment by NopeyTheBear** [comment]
i didn't want to be rude but it's the truth^^^^^^^^

**Comment by Rasgnarok** [comment]
If that is the only instance, I will stick to what I've said. You will be unbanned tomorrow, please remember to let a Senior Mod know of what edits on your Pokemon were stolen so they can be reverted. For next time, try not to steal.

**Comment by Rasgnarok** [comment]
You've now been unbanned.
