### ISSUE TITLE
I was falsely banned

### ISSUE THREAD

**Issue by Commmet** [ObliqueNET/Stratos#49]
Hello, my username is, Commet_ and I'd like to appeal because I was falsely banned. 
If I was banned truefully then I'd like to see the evidence. I haven't been breaking the economy, at least I don't think so. Thanks for your help, have a good day/night! 
<img width="809" alt="screen shot 2019-01-28 at 10 01 58 pm" src="https://user-images.githubusercontent.com/47131240/51881743-3bd6dd80-234a-11e9-8935-14c4ed137db3.png">

**Comment by fatyg5** [comment]
While investigating a town that had committed a mass duplication/economy breaking glitch, checking the logs on the chest that was being used to commit said glitch, your username came up as removing the duplicated items multiple times. For this, you were banned and will remain banned.

**Comment by Commmet** [comment]
aplEtToWn was my town, I personally don't remember duplicating items.

**Comment by Commmet** [comment]
Huh.
