### ISSUE TITLE
I believe I was falsely banned pt. 2 

### ISSUE THREAD

**Issue by Commmet** [ObliqueNET/Stratos#50]
My username, Commet_ and I believe I was falsely banned! Sorry if I am being bothersome as you probably have more important things to do but, can you somehow check the persons IP then look at my IP and see if it was me. Or, check which plot it was conduced in, I believe my towns name was aPleToWn the only plots I have access to is, my own and woofs1's and my towns land (that is not claimed by someone else in my town). Sorry again to have to write this for the second time but I do not admit to duplicating items. Have a good day/night!
<img width="868" alt="screen shot 2019-01-28 at 10 03 51 pm" src="https://user-images.githubusercontent.com/47131240/51938761-ed721f00-23db-11e9-8110-61ca11e50924.png">

**Comment by fatyg5** [comment]
As I've said before, the logs had shown your username, Commet_ accessing and removing items from the chest in question, meaning you had once had access to the town/chest/plot/whatever it was. Again, due to this, you will not be unbanned, the logs do not lie.

**Comment by Commmet** [comment]
What items were duped?
