### ISSUE TITLE
Unable to swap or Delete Moves from Move Tab on a Pokemon

### ISSUE THREAD

**Issue by Somerandomguy910** [ObliqueNET/Stratos#56]
When clicking on a move on the Move tab I am unable to Move the order or Delete any Moves.

![2019-02-03_10 45 54](https://user-images.githubusercontent.com/46073567/52178861-283fd280-27a1-11e9-9719-b943cada2979.png)

**Comment by fatyg5** [comment]
Yep, known Pixelmon bug. Fix awaiting 7.0.1.

**Comment by MattBlower** [comment]
Fixed for 7.0.1 thank you for reporting it.
