### ISSUE TITLE
Blazes and the Nether

### ISSUE THREAD

**Issue by JettisonedGames** [ObliqueNET/Stratos#59]
I wish to propose leaving blazes enabled in the nether from spawners, and simply remove the blaze rods from being able to be sold.  This would give players another way of getting experience levels, which are currently only obtained from smelting, training, and mining; none of which are particularly good when it comes to repairing mending items.
Edit: Would also give the combat oriented RPG skills a purpose

**Comment by fatyg5** [comment]
The issue with this is that, if we make them drop only experience, then mob loot has to be on. Meaning players can make mob farms in the nether and farm chicken, cows, etc. There's really not an easy work around for this, as I would most likely need to overwrite all the entity tables, if even possible.

**Comment by Fuklz** [comment]
There aren't many blaze spawners at all and definitely not an infinite nether so securing a blaze farm seems more like a contest that already ended than a thing for every player to do. Also the adage "kill pokemon for drops and sell them" gets less and less important over time, and removing blaze rods/powder from being sellable would only make farming like this feel worse.

Combat oriented RPG skills would literally only be used for killing more blazes until PVP is implemented, and using these skills on blazes only doesn't seem necessary or worth leveling. I would 100% prefer simply mining quartz over farming blazes for xp anyways.

It's going to be hard to ever make the combat rpg skills purposeful in a peaceful pixelmon server without implementing something like terra's hostile-mob world.

**Comment by fatyg5** [comment]
For now, we're gonna close this topic. We'll hopefully have a way in the future for things like this, but Nether blaze spawners are not the way.
