### ISSUE TITLE
My ban appeal IGN Soapy2712

### ISSUE THREAD

**Issue by Soapy2712** [ObliqueNET/Stratos#6]
Banned for: Xray

Reason to be unbanned: I did not use xray I use my minimap and dig straight down and see dungeons as they are open squares on the map I have talked to a staff member about this before and they even went mining with me, as minimaps are allowed thee is no reason I should be banned as long as I keep my entities off (which I do) 

Thank you for taking your time to read this,

Soapy2712

**Comment by Willynator** [comment]
I went in singleplayer just to test with your version of xaero's minimap and turned on cave settings.
Floating **below** surface level it still did not allow me to see anything but black regarding anything underground unless horizontal or a few blocks under. I do not believe it is possible under any normal circumstances to be able to walk on the surface and find any sort of dungeon without being at least a few blocks over the dungeon. Not to mention in order to find 8 bells in that exact manner would mean you would of had to of seen at minimum 8 dungeons in that manner which is also very unlikely and much more likely to of seen way over 8 dungeons.

**Comment by Soapy2712** [comment]
Is there any way i can show you like screenshots of me in singleplayer finding one

**Comment by Willynator** [comment]
sure you are able to attack files by dragging/dropping

**Comment by Soapy2712** [comment]
Ok also if you hold z it makes the map bigger and i have the zoom further out by pressing i a couple times i think

**Comment by Soapy2712** [comment]
Sorry for wait as i was having dinner with my family will get back to evidence now

**Comment by Soapy2712** [comment]
![2018-09-28 29](https://user-images.githubusercontent.com/43681755/46226149-4a3cca80-c353-11e8-9c08-617a52d8d526.png)
![2018-09-28 30](https://user-images.githubusercontent.com/43681755/46226155-4c068e00-c353-11e8-832a-18214d70ca8d.png)
![2018-09-28 31](https://user-images.githubusercontent.com/43681755/46226156-4dd05180-c353-11e8-9207-2ddf3a819cf1.png)
![2018-09-28 32](https://user-images.githubusercontent.com/43681755/46226157-4f9a1500-c353-11e8-8185-a4ec99e5e273.png)
![2018-09-28 33](https://user-images.githubusercontent.com/43681755/46226159-5163d880-c353-11e8-9e6a-1cf16d9eb3ab.png)
![2018-09-28 34](https://user-images.githubusercontent.com/43681755/46226163-545ec900-c353-11e8-81d7-4cf1155a520e.png)
![2018-09-28 35](https://user-images.githubusercontent.com/43681755/46226166-558ff600-c353-11e8-9a1a-41cfe2a771e2.png)
![2018-09-28 36](https://user-images.githubusercontent.com/43681755/46226167-5759b980-c353-11e8-84b7-715daac5b7f8.png)
![2018-09-28 37](https://user-images.githubusercontent.com/43681755/46226168-59237d00-c353-11e8-9050-acf63dd61adf.png)
![2018-09-28 38](https://user-images.githubusercontent.com/43681755/46226169-5aed4080-c353-11e8-916e-3d9e2326e8bb.png)
![2018-09-28 39](https://user-images.githubusercontent.com/43681755/46226173-5cb70400-c353-11e8-8472-b0ecaef30656.png)
![2018-09-28 40](https://user-images.githubusercontent.com/43681755/46226179-5de83100-c353-11e8-92e5-2388dc6e7526.png)
![2018-09-28 41](https://user-images.githubusercontent.com/43681755/46226184-5fb1f480-c353-11e8-9cc3-c04df8d3df10.png)
![2018-09-28 42](https://user-images.githubusercontent.com/43681755/46226187-60e32180-c353-11e8-875a-9dc4722fc0a4.png)

**Comment by Willynator** [comment]
That isnt showing what you were describing. It just showed you digging down and looking for mineshafts and searching the shafts

I cant under any circumstances from above ground find a dungeon to be able to dig straight down from as you said

![2018-09-28_12 16 29](https://user-images.githubusercontent.com/32440747/46227785-3af75600-c32e-11e8-9471-83890dae8a07.png)

**Comment by Willynator** [comment]
you can see me hovering over it underground and not seeing it popup unless I was to be pretty much right over it

**Comment by Soapy2712** [comment]
go level with it

**Comment by Soapy2712** [comment]
look at my playtime i have played for a long time

**Comment by Willynator** [comment]
`[Ultra]GoodSoapy[◆]: minimap and dig straight down they are a big open cube shape`
There are players with playtimes that dwarf yours and arent able to get anywhere near your amount of bells.

You said yourself you dig straight down into dungeons

**Comment by Soapy2712** [comment]
I said I dug straight down and looked for dungeons around me

**Comment by Willynator** [comment]
Even if that was the case which seems odd compared to your initial phrasing both on the server and here
bells do not spawn in mineshafts and with bells having a 1/15 chance of spawning inside a dungeon chest. There is easily a need to have to find over 100 dungeons in order to get 8 bells of any sort

**Comment by Soapy2712** [comment]
Ik but dungeons and mineshafts have a similar spawn rate, I really honestly didn't Xray and would love to be able to play on the server but I have real life stuff to do, homework etc as I am 13 and just like to play as a way to get away from real life. 


Tell the people of the server I didn't go down withought a fight but if u really want to ban an innocent player for xray  that has been supporting the server for a while now then do so don't think it would look good if in a bit I actually had the time in my life to film and post a youtube video of myself finding multiple dungeons my way in the future.

**Comment by Soapy2712** [comment]
You could ask Trapachu or Luciela aka dracona as they both went mining with me but how would that help :/

**Comment by Soapy2712** [comment]
also idk why id hack or xray pack on a server I have spent a significant amount of money on :/ money doesn't come easy when you're 13

**Comment by Willynator** [comment]
Ill ask this, if the chances to get 8 bells would equate to finding 120 dungeons and assuming it would take roughly 10 minutes between finding dungeons which is probably pretty short in terms of actual time. It would equate to a solid 20 hours of consistently finding dungeons after 10 minutes. 

Another thing is this isnt including the the bell or bells that would of been used for your initial lugia in that math

**Comment by Soapy2712** [comment]
Wow shouldnt have even mentioned the bells, now im banned for something i didnt do and cant ever come on a server ive spent   so much time and effort on,

**Comment by Soapy2712** [comment]
My pc is off now and have fully given up, staff were supposed to be helpful and enforce the rules not ban innocent ppl. Look at my history, nothing in that suggests id use hacks i have never been on a server with hacks nor ever installed them, my history makes me sound like an annoying kid which is what i am not some guy who wants to ruin the economy and the game for others

**Comment by Willynator** [comment]
I am just asking about facts as they are presenting themselves. People who play longer than you and grind hard have way less bells and the amount of bells you have are pretty insane to be found by one person. Its rare to hear of someone finding 2, 3 or even 4 bells but at least 9?

**Comment by Soapy2712** [comment]
I spent most of my time on bells almost all of my summer holiday on the server was me looking for bells. I went mining daily, for hours on end i worked hard to get them not cheat

**Comment by Soapy2712** [comment]
Also where i said minimap and dig straight down that was a basic summary of how i did it it is not like id write a paragraph on digging down and running about in caves looking for open squares with a mild green tint to the blocks

**Comment by Soapy2712** [comment]
The people with higher playtime do other things as i said earlier im more of a miner and a fisherman than a trainer/ breeder

**Comment by Rasgnarok** [comment]
I feel that this process is misunderstood. Appeals are here to discuss over what the ban reason was, and for parties to make amends where needed. 
Reason: You used a mod (regardless of what it is) to be able to see into the ground and dig down to get bells. That's using xray. And xray is a cheat according to our rules.

Appeals are to make the banned player understand why they were banned, and why it was unfair to other players. Not to argue over how or why you used the hack that got you banned. If you want to appeal, say that you were wrong/didn't know it was and then make amends for it, that's fair and it's the point of this. Feel free to tag me here with a reply, Soapy.

**Comment by Soapy2712** [comment]
But ras I did not hack or use any xray mod. That's what I don't get, you need to be 100% certain before banning a player

**Comment by Rasgnarok** [comment]
Right, I realize no one showed you why: 
![image](https://user-images.githubusercontent.com/18584380/46249652-c76f4a80-c3fa-11e8-8b1a-7a667ada3b54.png)

This is a chat of you saying you use your minimap to dig straight down to the square caverns you see through the ground.

**Comment by Soapy2712** [comment]
Yes but minimaps are allowed

**Comment by Soapy2712** [comment]
and I cant see them through the ground

**Comment by Soapy2712** [comment]
i can see them when level with them while mining

**Comment by Soapy2712** [comment]
it was a misunderstanding

**Comment by Rasgnarok** [comment]
Note, I did see the screenshots above, but some where standing on trees or floating nearby the surface. I just want one of you standing still right on the last surface block above a mineshaft.

**Comment by Soapy2712** [comment]
kk

**Comment by Soapy2712** [comment]
If i have an open block above me while below ground level that leads to surface it does not let me see caves

**Comment by Rasgnarok** [comment]
Right, so basically if your player position can see the air, the minimap doesn't activate underground mode?

**Comment by Soapy2712** [comment]
If it is undergound and has air space directly above it leading to surface

**Comment by Soapy2712** [comment]
![2018-09-29](https://user-images.githubusercontent.com/43681755/46249785-dc61d300-c426-11e8-8660-822976594d76.png)
![2018-09-29 1](https://user-images.githubusercontent.com/43681755/46249786-de2b9680-c426-11e8-9d2a-e37c6632417e.png)
![2018-09-29 2](https://user-images.githubusercontent.com/43681755/46249788-dff55a00-c426-11e8-9bd3-0fe535608b97.png)
![2018-09-29 3](https://user-images.githubusercontent.com/43681755/46249790-e1268700-c426-11e8-8649-0da0f1337e88.png)

**Comment by Rasgnarok** [comment]
That's actually a really cool behaviour of the minimap, and quite smart of you. I'll amend the rule to make this clearer -> if cavern mode is enabled when your position sees the air, it's xray.

As for your ban, you are now unbanned. On behalf of everyone, I am sorry for the terribly long appeal, it should have been straightforward and simple, like the chat we just had. Thanks for your patience.
