### ISSUE TITLE
Gastly breeding bug

### ISSUE THREAD

**Issue by CaptainCrafter1** [ObliqueNET/Stratos#60]
So, i have Gastlys in breeder and they are not apperaring in their breeder, nor are they making any eggs, i checked on Terra and there breeders work normaly, i tried to take them out and put them in again, i destroyed ranch block and place it back, also tried to throw gastlys out before putting them into breeder, but none of this worked

**Comment by CaptainCrafter1** [comment]
Aparently solved by evolving my gastlys into gengars

**Comment by Rasgnarok** [comment]
Breeding issues were fixed with 7.0.1 too, closing
