### ISSUE TITLE
Trainer Card (U Keybind) not displaying correct pokedex number and balance.

### ISSUE THREAD

**Issue by Forensiic** [ObliqueNET/Stratos#63]
![dexrank 1](https://user-images.githubusercontent.com/47290518/52309292-87921400-2954-11e9-8c3e-27d06abd502f.PNG)
![dexrank 2](https://user-images.githubusercontent.com/47290518/52309303-89f46e00-2954-11e9-9771-23b6648cf722.PNG)
![balance](https://user-images.githubusercontent.com/47290518/52309306-8c56c800-2954-11e9-91b4-f34ae140ce5b.PNG)
![2019-02-05_21 53 28](https://user-images.githubusercontent.com/47290518/52323093-8bdc2280-2990-11e9-8903-7f750b51d9a7.png)
So I can't actually buy from the server shop.

**Comment by MattBlower** [comment]
Is fixed fore 7.0.1 thank you for reporting this.

**Comment by fatyg5** [comment]
Fixed, the balance may be broken, but that's a whole 'nother issue.
