### ISSUE TITLE
XP Boost not working with EXP All/EXP Share

### ISSUE THREAD

**Issue by DannyPX** [ObliqueNET/Stratos#67]
Pokemons in party that doesnt get the exp bonus (from exp boosts) when defeating pokemons, only the pokemon that defeated the opponent gets the bonus.
I checked the exp increase in Summary aswell to be sure.
![image](https://user-images.githubusercontent.com/47347980/52367064-7d067600-2a4b-11e9-8641-f476603784c2.png)

**Comment by Forensiic** [comment]
This is still ongoing. 
![EXP Boost](https://user-images.githubusercontent.com/47290518/55676780-8582fd80-5890-11e9-9aff-f7c0f5067c38.PNG)

**Comment by fatyg5** [comment]
Fixed in a coming update.
