### ISSUE TITLE
Some Move Tutors missing

### ISSUE THREAD

**Issue by DannyPX** [ObliqueNET/Stratos#68]
The Move Tutors at the Rock Gym and Battle Frontier disappeared, others are still there.

![](https://i.gyazo.com/23db42c52f500a474a1362bc732b31c6.jpg)
![](https://i.gyazo.com/06ff25cb4560fa77b7e32916f8841827.jpg)
![](https://i.gyazo.com/d5bc7c1ee7470523adf258a615766a58.jpg)
![](https://i.gyazo.com/04319b814e503a4ffc0f59f5a2c38793.png)

**Comment by MattBlower** [comment]
side effect bug of 7.0.0, they will be back up and running as soon as possible, thank you for reporting this.

**Comment by fatyg5** [comment]
Fixed.
