### ISSUE TITLE
EXP Bar for Level 100's

### ISSUE THREAD

**Issue by MykingofmE** [ObliqueNET/Stratos#71]
While the exp bars in the summary page were fixed in 7.0.1, I noticed that the issue of the battle exp bar still persists after said update.  Just thought that I would let this fact be known.
![screenshot 16](https://user-images.githubusercontent.com/46580283/52515501-09e33800-2be2-11e9-8410-feb611a110c2.png)

**Comment by fatyg5** [comment]
Fixed.
