### ISSUE TITLE
Oak leaves appear grey instead of green.

### ISSUE THREAD

**Issue by Forensiic** [ObliqueNET/Stratos#72]
![leaves](https://user-images.githubusercontent.com/47290518/52525587-8ae11480-2c60-11e9-8067-d9d310a9007d.PNG)

**Comment by fatyg5** [comment]
Believe this is how leaves show up when an invalid biome is present(drop GUI doesn't have a biome), they turn gray. Not sure if there's much that can be done about it.

**Comment by Rasgnarok** [comment]
Not much we can do, closing.
