### ISSUE TITLE
Ban Review (Second_Entity)

### ISSUE THREAD

**Issue by UglyGods** [ObliqueNET/Stratos#73]
This morning I was online the server when I decided to use the /invitefriend command to invite a few of my dorm mates to get on the server. I told them about the rewards so they logged in as soon as they could and they went to morning training. I was rearranging some chests when I was  kicked and banned for the reason below. As mentioned earlier, I live in a dorm with 4 of my close friends that all share the same WIFI. I believe this might have set something off in your system to cause the belief that we were alting but that was not the case. Hopefully this is just a misunderstanding and I can explain something further if need be. 
![2019-02-09_17 50 01](https://user-images.githubusercontent.com/47489564/52528483-8f272500-2c94-11e9-9b21-28255fa5218c.png)

**Comment by fatyg5** [comment]
I'm really finding this difficult to believe. I checked all the accounts associated with your IP, 2 logged out in the same location, with empty inventories, almost as if they had given their items to another player and then logged off. Then I TP to another one and find the 3 other associated accounts standing like this https://cdn.discordapp.com/attachments/479746459521253388/543874592154845233/unknown.png all with the same 4 items in their inventory and the rest of the inventory missing, while your account was the only one moving. I really don't think this is a coincidence.

**Comment by UglyGods** [comment]
> I'm really finding this difficult to believe. I checked all the accounts associated with your IP, 2 logged out in the same location, with empty inventories, almost as if they had given their items to another player and then logged off. Then I TP to another one and find the 3 other associated accounts standing like this https://cdn.discordapp.com/attachments/479746459521253388/543874592154845233/unknown.png all with the same 4 items in their inventory and the rest of the inventory missing, while your account was the only one moving. I really don't think this is a coincidence.

As I said in the post, they were afking while they did training and I stayed on to do some work around my base. As fishy as it is these guys were planning to stay on to play longer. As for the other two, I had invited them two people who did not even enjoy mc anymore (let alone a pixelmon server) and they gave me their rewards and left. Although, know that I look back at it, it was scummy af. I can assure you that no foul play was intended at the time and will gladly get rid of any profits if its comes to it.

**Comment by fatyg5** [comment]
I honestly didn't realize this was reopened after it was closed. If you actually check these, please give me your username otherwise I'll close this.

**Comment by LegitimateAlt** [comment]
This afternoon I was banned from the server, apparently people had been messaging me to verify my account. I haven't been playing the game for long and didn't realise that people were trying to talk to me as I just tend to ignore the chat and play the game by myself. I am sorry for the inconvenience and know that my user name has probably caused some confusion as well but I hope that this can be fixed soon and I promise that I will be checking the chat more! 
<img width="859" alt="Screenshot 2019-06-16 at 17 32 18" src="https://user-images.githubusercontent.com/51885757/59566877-d0be4700-905d-11e9-82a3-ad9cb9c938b6.png">

**Comment by Hiroku** [comment]
You've been unbanned; I'm sorry you got banned before we actually asked your brother about your account.

**Comment by LegitimateAlt** [comment]
Thank you, and don't worry about it. It was pretty stupid of me on
hindsight to not realise the username would cause confusion and to not
check the chat. Thanks again for unbanning me, I really appreciate it.
