### ISSUE TITLE
Pokemon Duplicated in Pc

### ISSUE THREAD

**Issue by LordLlama17** [ObliqueNET/Stratos#75]
I caught a Nincada in a premier ball and the chat kept repeating that the Nincada was being sent to the PC because I had no space in my party. I checked my PC and there were Nincadas filling the PC to box 30

**Comment by fatyg5** [comment]
Interesting.

**Comment by fatyg5** [comment]
Haven't seen this reported in forever, I assume we made fixes to it. Gonna close off that basis, reopen it if something similar happens.
