### ISSUE TITLE
Ban appeal 2

### ISSUE THREAD

**Issue by XxDonutPvPxX** [ObliqueNET/Stratos#76]
Sorry about the first one but i honestly feel attacked when everyone starts saying stuff about me. I was trying to stop but then everyone, and I mean everyone was chiming in to attack me. All I’m asking for is 1 more chance and then I don’t care what will happen to me. I will prove to you that I can be changed. All I’m asking for is 24 hours. I don’t even care if I’m muted for the whole time. Again, I’m sorry about this whole thing as I was wrong. Please tell volca and fuklz that I am sorry.

**Comment by fatyg5** [comment]
This is denied. You will not be unbanned. You've gone far enough to warrant a ban (usually we don't even ban on first time things), and thus it will stay this way. Do not make any more tickets.

**Comment by XxDonutPvPxX** [comment]
Please man I’m begging you. I’m very sorry and was wrong in every way.
