### ISSUE TITLE
Can't join Oblique server anymore.

### ISSUE THREAD

**Issue by LordLlama17** [ObliqueNET/Stratos#79]
I was exploring Stratos when I found a place called Rivendell. I saw a Nether portal and proceded to enter it. When I loaded in it said I died and it said I suffocated in a wall. I tried to respawn multiple times but couldn't.  I left the server and tried to reload it but now I keep getting disconnected when trying to join. Will I have to restart or is there a way to fix this?

**Comment by fatyg5** [comment]
Please try logging in now.

**Comment by LordLlama17** [comment]
It still says “disconnected” after taking a while to load. Do you want me to send you the log from today?

**Comment by fatyg5** [comment]
Please.

**Comment by LordLlama17** [comment]
[techniclauncher_2019-02-10.log](https://github.com/ObliqueNET/Stratos/files/2849582/techniclauncher_2019-02-10.log)
[latest.log](https://github.com/ObliqueNET/Stratos/files/2849586/latest.log)

**Comment by fatyg5** [comment]
Can you try now? We've restarted the server

**Comment by LordLlama17** [comment]
I'm back on! Thank you so much.
