### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Rabidrounds785** [ObliqueNET/Stratos#8]
I was basically told this thing called a radar was legal in the server, so I believe him and downloaded it, but I didn't read the rules correctly because I got banned. (Basically I got scammed so I got banned). Here was the chat log of that happening. 
[Poke]HustL: i'm gonna go equip pokeradar
[Ultra]Rabidrounds785: Ok,
[Ultra]Rabidrounds785: wait!
[Ultra]Rabidrounds785: theres a radar
[Ultra]kjekken: what does pokeradar do?
[Poke]HustL: because i had to redownload my modpack
[Ultra]Rabidrounds785: Whats the pokeradar
[Poke]HustL: so it disappeared
[Poke]HustL: it shows all nearby pokemon on your map
ETC
ETC
[Ultra]Rabidrounds785: Do i need a minimap mod for the pokeradar
[Poke]HustL: no, it comes with it
[Ultra]Rabidrounds785: oh
[Poke]HustL: yeah it's great
[Ultra]kjekken: is the mod allowed on this server?
[Poke]HustL: Yeah

**Comment by Rabidrounds785** [comment]
k

**Comment by Djmaster1001** [comment]
unbanned plz
