### ISSUE TITLE
Pixelmon Fossils and Cleaners

### ISSUE THREAD

**Issue by PoliSwag** [ObliqueNET/Stratos#80]
I hope that I am doing this right since this is my first time on here but a few moments ago I found a fossil ore block and used my fortune pick on it and got 2 fossils I then went to my home and tried to clean them but every time I would put it into the machine It won't clean them and I get the covered fossils back.

**Comment by JettisonedGames** [comment]
Just looking for some more details here; Did you leave it in the machine until it stopped moving and its model changed?  The time on the server may make them sit a bit longer, but if you leave them in there for a few extra seconds, that may fix your problem.

**Comment by PoliSwag** [comment]
Oh, I forgot to check this lol, It fixed itself but when it happened all it did was spin it, showed that it was cleaned and when I grabbed it after it cleaned it spat the covered one at me instead. But again it happened to fix itself sometime 2 days ago so im all good now :)
