### ISSUE TITLE
Healing Bug

### ISSUE THREAD

**Issue by SacredSilverr** [ObliqueNET/Stratos#81]
When healing and I'm holding a item, and it finishes healing, my item that I was holding disappears to thin air. How this happens is that I like to move around when healing my pokemons, so for me to be able to move while healing, I click on the healer, and the quickly on my pc. That allows me to freely move around in a small radius. And I was grabbed a diamond block to make myself a healer, that's when it disappeared, right after the healer finished healing, once again.

**Comment by MykingofmE** [comment]
The times I recreated this situation (which wasn't many, no clue how you click that fast), my held item didn't disappear.

**Comment by SacredSilverr** [comment]
Let me add more information that I forgot to mention. When this happened, I was in the process of putting my diamond block in my player inventory from my chest inventory. When that happened, I was holding the item with the mouse curser. While doing that, when the healing process was done, it forces me out of my chest, and that's when my diamond block went by by. I've already tried relogging by the way.

**Comment by Rasgnarok** [comment]
I need this retested, whenever someone can get to it.

**Comment by fatyg5** [comment]
Unable to reproduce.
