### ISSUE TITLE
Unban Request

### ISSUE THREAD

**Issue by JapaneseTourism** [ObliqueNET/Stratos#83]
I had changed my name to JapaneseTourism and I started advertising Japan on the Stratos Server. I started to try to be funny with it but I took things to far while talking about porn. I was new to the server and I was not aware of all the rules. I didn't know about the chat rules and I was banned on the Stratos Server. I apologize for my actions and I request to be unbanned. My username on minecraft is JapaneseTourism.

**Comment by fatyg5** [comment]
Due to the comments made, I don't believe it was "taken too far", it was too far from the beginning and, even if not reading the rules, comments were way too far morally speaking. For that, you won't be unbanned.

**Comment by JapaneseTourism** [comment]
Wow I was banned for a joke. What are you, a liberal or something?

**Comment by Hiroku** [comment]
Good thing we didn't unban you

**Comment by JapaneseTourism** [comment]
Why can't you guys just mute me or something? I made a joke that you guys think is offensive so I am automatically banned with no second chance? Doesn't it seem a little bit harsh to you guys? I just want to play some pixelmon with my friends.

**Comment by JapaneseTourism** [comment]
Haven't you ever heard of a warning? I'll take this up with your superiors sir.

**Comment by fatyg5** [comment]
Good luck!
