### ISSUE TITLE
Unban Request

### ISSUE THREAD

**Issue by TylerVu** [ObliqueNET/Stratos#85]
Hey all! I am appealing for a ban on the Stratos Server. I was using the ForgeWurst, and I shouldn't have on the server. I was originally using it on another server at the time for killaura, autosprint, and fullbrightness. I forgot to take it out of the mod folder and used it on this server. I am extremely sorry as it won't happen again.

**Comment by fatyg5** [comment]
Your username is?

**Comment by TylerVu** [comment]
DogeTheDoge

**Comment by MrBritish8** [comment]
Sorry for the late reply, but if you can prove you have removed the mod we will pardon you, this will be your only chance. if you are caught again it not be pardoned

**Comment by W4nkey** [comment]
I'm not sure I'm doing this right but I just got banned for "Racial Slurs" which is not the case. I never said anything Racist to anyone. I'd like to be unbanned because I worked hard for what i had in that game and it is unfair to have all of it be lost because of miscomunication.

**Comment by Forensiic** [comment]
It's best if you create your own thread, Press the green "New Issue" button and submit an appeal.
