### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by FreeHawkie** [ObliqueNET/Stratos#9]
Ign: FreeHawkie (was ItsHawkie when banned)
I got banned for apparently x-raying a few months ago.(Before yall merged) I didn't understand why I was banned for x-raying when i was eff 5 mining with my thunderstone set. I was unbanned because they said they "didnt have enough proof." I played for a few days after I got unbanned then went on vacation, when i got back i saw i was banned from the server saying "it was a mistake unbanning you." Some people told me it was because I told a staff member I used x-ray when i really didn't i just said "like my x-ray" then they would laugh cause they knew i was joking around, but one staff in the call thought i was being serious and i think messages Faty.
-Hawkie

**Comment by lolanonymous** [comment]
After much internal discussion we have decided to deny your appeal. Not only were you banned _multiple times_ for xray, you also had attitude issues and made jokes that were not welcome on the server.
