### ISSUE TITLE
[Discord] Discord4J$Discord4JLogger IOException: Broken pipe

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Stratos#94]
https://gist.github.com/Vohras2/349c081351239360edb7241068b1d4d3

**Comment by Rasgnarok** [comment]
This is something I am unsure about, maybe @Hiroku has a clue.

**Comment by Hiroku** [comment]
It's not serious, happens sometimes and the error is wrapped so it doesn't cause any damage
