### ISSUE TITLE
[ObliqueCore] NumberFormatException at hiroku.common.obliquecore.commands.LinkExecutor

### ISSUE THREAD

**Issue by Vohras2** [ObliqueNET/Stratos#98]
https://gist.github.com/Vohras2/c9a8b35e29c9bb3d465d6a219829cf4a

**Comment by Hiroku** [comment]
It's caused by someone using /link manually, it isn't a serious issue

**Comment by Hiroku** [comment]
Methodology has been redone, doesn't use a /link command anymore
